//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package eu.datex2.schema._1_0._1_0;

public enum CountryEnum {


    /**
     * Austria
     * 
     */
    
    AT("at"),

    /**
     * Belgium
     * 
     */
    
    BE("be"),

    /**
     * Bulgaria
     * 
     */
    
    BG("bg"),

    /**
     * Switzerland
     * 
     */
    
    CH("ch"),

    /**
     * Serbia and Montenegro
     * 
     */
    
    CS("cs"),

    /**
     * Cyprus
     * 
     */
    
    CY("cy"),

    /**
     * Czech Republic
     * 
     */
    
    CZ("cz"),

    /**
     * Germany
     * 
     */
    
    DE("de"),

    /**
     * Denmark
     * 
     */
    
    DK("dk"),

    /**
     * Estonia
     * 
     */
    
    EE("ee"),

    /**
     * Spain
     * 
     */
    
    ES("es"),

    /**
     * Finland
     * 
     */
    
    FI("fi"),

    /**
     * Faroe Islands
     * 
     */
    
    FO("fo"),

    /**
     * France
     * 
     */
    
    FR("fr"),

    /**
     * Great Britain
     * 
     */
    
    GB("gb"),

    /**
     * Guernsey
     * 
     */
    
    GG("gg"),

    /**
     * Gibralta
     * 
     */
    
    GI("gi"),

    /**
     * Greece
     * 
     */
    
    GR("gr"),

    /**
     * Croatia
     * 
     */
    
    HR("hr"),

    /**
     * Hungary
     * 
     */
    
    HU("hu"),

    /**
     * Ireland
     * 
     */
    
    IE("ie"),

    /**
     * Isle Of Man
     * 
     */
    
    IM("im"),

    /**
     * Iceland
     * 
     */
    
    IS("is"),

    /**
     * Italy
     * 
     */
    
    IT("it"),

    /**
     * Jersey
     * 
     */
    
    JE("je"),

    /**
     * Lichtenstein
     * 
     */
    
    LI("li"),

    /**
     * Lithuania
     * 
     */
    
    LT("lt"),

    /**
     * Luxembourg
     * 
     */
    
    LU("lu"),

    /**
     * Latvia
     * 
     */
    
    LV("lv"),

    /**
     * Morocco
     * 
     */
    
    MA("ma"),

    /**
     * Monaco
     * 
     */
    
    MC("mc"),

    /**
     * Macedonia
     * 
     */
    
    MK("mk"),

    /**
     * Malta
     * 
     */
    
    MT("mt"),

    /**
     * Netherlands
     * 
     */
    
    NL("nl"),

    /**
     * Norway
     * 
     */
    
    NO("no"),

    /**
     * Poland
     * 
     */
    
    PL("pl"),

    /**
     * Portugal
     * 
     */
    
    PT("pt"),

    /**
     * Romania
     * 
     */
    
    RO("ro"),

    /**
     * Sweden
     * 
     */
    
    SE("se"),

    /**
     * Slovenia
     * 
     */
    
    SI("si"),

    /**
     * Slovakia
     * 
     */
    
    SK("sk"),

    /**
     * San Marino
     * 
     */
    
    SM("sm"),

    /**
     * Turkey
     * 
     */
    
    TR("tr"),

    /**
     * Vatican City State
     * 
     */
    
    VA("va"),

    /**
     * Other than as defined in this enumeration.
     * 
     */
    
    OTHER("other");
    private final String value;

    CountryEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CountryEnum fromValue(String v) {
        for (CountryEnum c: CountryEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
