//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package eu.datex2.schema._1_0._1_0;

public enum DelayCodeEnum {


    /**
     * Delay between one hour and three hours.
     * 
     */
    
    DELAY_BETWEEN_ONE_HOUR_AND_THREE_HOURS("delayBetweenOneHourAndThreeHours"),

    /**
     * Delay between thirty minutes and one hour.
     * 
     */
    
    DELAY_BETWEEN_THIRTY_MINUTES_AND_ONE_HOUR("delayBetweenThirtyMinutesAndOneHour"),

    /**
     * Delay between three hours and six hours.
     * 
     */
    
    DELAY_BETWEEN_THREE_HOURS_AND_SIX_HOURS("delayBetweenThreeHoursAndSixHours"),

    /**
     * Delay less than thirty minutes.
     * 
     */
    
    DELAY_LESS_THAN_THIRTY_MINUTES("delayLessThanThirtyMinutes"),

    /**
     * Delay longer than six hours.
     * 
     */
    
    DELAY_LONGER_THAN_SIX_HOURS("delayLongerThanSixHours"),

    /**
     * Negligible delay.
     * 
     */
    
    NEGLIGIBLE("negligible");
    private final String value;

    DelayCodeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DelayCodeEnum fromValue(String v) {
        for (DelayCodeEnum c: DelayCodeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
