//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package eu.datex2.schema._1_0._1_0;

public enum DelaysTypeEnum {


    /**
     * Delays on the road network as a result of any situation which causes hold-ups.
     * 
     */
    
    DELAYS("delays"),

    /**
     * Delays on the road network whose predicted duration cannot be estimated.
     * 
     */
    
    DELAYS_OF_UNCERTAIN_DURATION("delaysOfUncertainDuration"),

    /**
     * Delays on the road network of unusual severity.
     * 
     */
    
    LONG_DELAYS("longDelays"),

    /**
     * Delays on the road network of abnormally unusual severity.
     * 
     */
    
    VERY_LONG_DELAYS("veryLongDelays");
    private final String value;

    DelaysTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DelaysTypeEnum fromValue(String v) {
        for (DelaysTypeEnum c: DelaysTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
