//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package eu.datex2.schema._1_0._1_0;

public enum DirectionEnum {


    /**
     * In the anticlockwise direction of travel on a ring road.
     * 
     */
    
    ANTICLOCKWISE("anticlockwise"),

    /**
     * In the clockwise direction of travel on a ring road.
     * 
     */
    
    CLOCKWISE("clockwise"),

    /**
     * In the north bound direction of travel.
     * 
     */
    
    NORTH_BOUND("northBound"),

    /**
     * In the north east bound direction of travel.
     * 
     */
    
    NORTH_EAST_BOUND("northEastBound"),

    /**
     * In the east bound direction of travel.
     * 
     */
    
    EAST_BOUND("eastBound"),

    /**
     * In the south east bound direction of travel.
     * 
     */
    
    SOUTH_EAST_BOUND("southEastBound"),

    /**
     * In the south bound direction of travel.
     * 
     */
    
    SOUTH_BOUND("southBound"),

    /**
     * In the south west bound direction of travel.
     * 
     */
    
    SOUTH_WEST_BOUND("southWestBound"),

    /**
     * In the west bound direction of travel.
     * 
     */
    
    WEST_BOUND("westBound"),

    /**
     * In the north west bound direction of travel.
     * 
     */
    
    NORTH_WEST_BOUND("northWestBound");
    private final String value;

    DirectionEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DirectionEnum fromValue(String v) {
        for (DirectionEnum c: DirectionEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
