//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package eu.datex2.schema._1_0._1_0;

public enum InformationUsageEnum {

	/**
	 * For broadcast usage to any interested party.
	 * 
	 */
	
	BROADCAST("broadcast"),

	/**
	 * For internal usage within the recipient organisation.
	 * 
	 */
	
	INTERNAL("internal"),

	/**
	 * For support of Internet services.
	 * 
	 */
	
	INTERNET("internet"),

	/**
	 * For variable message sign usage.
	 * 
	 */
	
	VARIABLE_MESSAGE_SIGN("variableMessageSign");
	private final String value;

	InformationUsageEnum(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static InformationUsageEnum fromValue(String v) {
		for (InformationUsageEnum c : InformationUsageEnum.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
