//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package eu.datex2.schema._1_0._1_0;

import uk.org.siri.siri.ServiceConditionEnumeration;

public enum InformationStatusEnum {


    /**
     * The information is real. It is not a test or exercise.
     * 
     */
    
    REAL("real"),

    /**
     * The information is part of an exercise which is for testing security.
     * 
     */
    
    SECURITY_EXERCISE("securityExercise"),

    /**
     * The information is part of an exercise which includes tests of associated technical subsystems.
     * 
     */
    
    TECHNICAL_EXERCISE("technicalExercise"),

    /**
     * The information is part of a test for checking the exchange of this type of information.
     * 
     */
    
    TEST("test");
    private final String value;

    InformationStatusEnum(String v) {
        value = v;
    }

    public static InformationStatusEnum fromString(String v) {
		if (v != null) {
			for (InformationStatusEnum c : InformationStatusEnum.values()) {
				if (v.equalsIgnoreCase(c.toString())) {
			          return c;
			    }				
			}
		}
		throw new IllegalArgumentException(v);
	}

	@Override
	public String toString() {
		return value;
	}

}
