//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package eu.datex2.schema._1_0._1_0;

public enum MonthOfYearEnum {


    /**
     * The month of January.
     * 
     */
    
    JANUARY("january"),

    /**
     * The month of February.
     * 
     */
    
    FEBRUARY("february"),

    /**
     * The month of March.
     * 
     */
    
    MARCH("march"),

    /**
     * The month of April.
     * 
     */
    
    APRIL("april"),

    /**
     * The month of May.
     * 
     */
    
    MAY("may"),

    /**
     * The month of June.
     * 
     */
    
    JUNE("june"),

    /**
     * The month of July.
     * 
     */
    
    JULY("july"),

    /**
     * The month of August.
     * 
     */
    
    AUGUST("august"),

    /**
     * The month of September.
     * 
     */
    
    SEPTEMBER("september"),

    /**
     * The month of October.
     * 
     */
    
    OCTOBER("october"),

    /**
     * The month of November.
     * 
     */
    
    NOVEMBER("november"),

    /**
     * The month of December.
     * 
     */
    
    DECEMBER("december");
    private final String value;

    MonthOfYearEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MonthOfYearEnum fromValue(String v) {
        for (MonthOfYearEnum c: MonthOfYearEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
