//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package eu.datex2.schema._1_0._1_0;

public class ReferencePointPrimaryLocation {


    protected ReferencePoint referencePoint;
    protected ExtensionType referencePointPrimaryLocationExtension;

    /**
     * Gets the value of the referencePoint property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencePoint }
     *     
     */
    public ReferencePoint getReferencePoint() {
        return referencePoint;
    }

    /**
     * Sets the value of the referencePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencePoint }
     *     
     */
    public void setReferencePoint(ReferencePoint value) {
        this.referencePoint = value;
    }

    /**
     * Gets the value of the referencePointPrimaryLocationExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getReferencePointPrimaryLocationExtension() {
        return referencePointPrimaryLocationExtension;
    }

    /**
     * Sets the value of the referencePointPrimaryLocationExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setReferencePointPrimaryLocationExtension(ExtensionType value) {
        this.referencePointPrimaryLocationExtension = value;
    }

}
