//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package eu.datex2.schema._1_0._1_0;

import java.util.ArrayList;
import java.util.List;
public class ReferencePoint {

    
    protected String referencePointIdentifier;
    protected ReferencePoint.AdministrativeArea administrativeArea;
    protected ReferencePoint.RoadName roadName;
    protected String roadNumber;
    protected DirectionEnum directionBound;
    protected ReferencePointDirectionEnum directionRelative;
    protected Float distanceFromPrevious;
    protected Float distanceToNext;
    protected Boolean elevatedRoadSection;
    protected ReferencePoint.ReferencePointDescription referencePointDescription;
    protected Float referencePointDistance;
    protected ExtensionType referencePointExtension;

    /**
     * Gets the value of the referencePointIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencePointIdentifier() {
        return referencePointIdentifier;
    }

    /**
     * Sets the value of the referencePointIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencePointIdentifier(String value) {
        this.referencePointIdentifier = value;
    }

    /**
     * Gets the value of the administrativeArea property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencePoint.AdministrativeArea }
     *     
     */
    public ReferencePoint.AdministrativeArea getAdministrativeArea() {
        return administrativeArea;
    }

    /**
     * Sets the value of the administrativeArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencePoint.AdministrativeArea }
     *     
     */
    public void setAdministrativeArea(ReferencePoint.AdministrativeArea value) {
        this.administrativeArea = value;
    }

    /**
     * Gets the value of the roadName property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencePoint.RoadName }
     *     
     */
    public ReferencePoint.RoadName getRoadName() {
        return roadName;
    }

    /**
     * Sets the value of the roadName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencePoint.RoadName }
     *     
     */
    public void setRoadName(ReferencePoint.RoadName value) {
        this.roadName = value;
    }

    /**
     * Gets the value of the roadNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadNumber() {
        return roadNumber;
    }

    /**
     * Sets the value of the roadNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoadNumber(String value) {
        this.roadNumber = value;
    }

    /**
     * Gets the value of the directionBound property.
     * 
     * @return
     *     possible object is
     *     {@link DirectionEnum }
     *     
     */
    public DirectionEnum getDirectionBound() {
        return directionBound;
    }

    /**
     * Sets the value of the directionBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectionEnum }
     *     
     */
    public void setDirectionBound(DirectionEnum value) {
        this.directionBound = value;
    }

    /**
     * Gets the value of the directionRelative property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencePointDirectionEnum }
     *     
     */
    public ReferencePointDirectionEnum getDirectionRelative() {
        return directionRelative;
    }

    /**
     * Sets the value of the directionRelative property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencePointDirectionEnum }
     *     
     */
    public void setDirectionRelative(ReferencePointDirectionEnum value) {
        this.directionRelative = value;
    }

    /**
     * Gets the value of the distanceFromPrevious property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDistanceFromPrevious() {
        return distanceFromPrevious;
    }

    /**
     * Sets the value of the distanceFromPrevious property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDistanceFromPrevious(Float value) {
        this.distanceFromPrevious = value;
    }

    /**
     * Gets the value of the distanceToNext property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDistanceToNext() {
        return distanceToNext;
    }

    /**
     * Sets the value of the distanceToNext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDistanceToNext(Float value) {
        this.distanceToNext = value;
    }

    /**
     * Gets the value of the elevatedRoadSection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isElevatedRoadSection() {
        return elevatedRoadSection;
    }

    /**
     * Sets the value of the elevatedRoadSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setElevatedRoadSection(Boolean value) {
        this.elevatedRoadSection = value;
    }

    /**
     * Gets the value of the referencePointDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencePoint.ReferencePointDescription }
     *     
     */
    public ReferencePoint.ReferencePointDescription getReferencePointDescription() {
        return referencePointDescription;
    }

    /**
     * Sets the value of the referencePointDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencePoint.ReferencePointDescription }
     *     
     */
    public void setReferencePointDescription(ReferencePoint.ReferencePointDescription value) {
        this.referencePointDescription = value;
    }

    /**
     * Gets the value of the referencePointDistance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getReferencePointDistance() {
        return referencePointDistance;
    }

    /**
     * Sets the value of the referencePointDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setReferencePointDistance(Float value) {
        this.referencePointDistance = value;
    }

    /**
     * Gets the value of the referencePointExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getReferencePointExtension() {
        return referencePointExtension;
    }

    /**
     * Sets the value of the referencePointExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setReferencePointExtension(ExtensionType value) {
        this.referencePointExtension = value;
    }


    public static class AdministrativeArea {


        protected List<ReferencePoint.AdministrativeArea.Value> value;

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReferencePoint.AdministrativeArea.Value }
         * 
         * 
         */
        public List<ReferencePoint.AdministrativeArea.Value> getValue() {
            if (value == null) {
                value = new ArrayList<ReferencePoint.AdministrativeArea.Value>();
            }
            return this.value;
        }


        public static class Value {


            protected String value;
            protected String lang;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the lang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLang() {
                return lang;
            }

            /**
             * Sets the value of the lang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLang(String value) {
                this.lang = value;
            }

        }

    }



    public static class ReferencePointDescription {


        protected List<ReferencePoint.ReferencePointDescription.Value> value;

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReferencePoint.ReferencePointDescription.Value }
         * 
         * 
         */
        public List<ReferencePoint.ReferencePointDescription.Value> getValue() {
            if (value == null) {
                value = new ArrayList<ReferencePoint.ReferencePointDescription.Value>();
            }
            return this.value;
        }


           public static class Value {

   
            protected String value;
            protected String lang;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the lang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLang() {
                return lang;
            }

            /**
             * Sets the value of the lang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLang(String value) {
                this.lang = value;
            }

        }

    }

   
    public static class RoadName {


        protected List<ReferencePoint.RoadName.Value> value;

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReferencePoint.RoadName.Value }
         * 
         * 
         */
        public List<ReferencePoint.RoadName.Value> getValue() {
            if (value == null) {
                value = new ArrayList<ReferencePoint.RoadName.Value>();
            }
            return this.value;
        }

        public static class Value {


            protected String value;
            protected String lang;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the lang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLang() {
                return lang;
            }

            /**
             * Sets the value of the lang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLang(String value) {
                this.lang = value;
            }

        }

    }

}
