//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package eu.datex2.schema._1_0._1_0;

public enum TrafficRestrictionTypeEnum {


    /**
     * The carriageway is totally obstructed in the specified direction due to an unplanned event.
     * 
     */
    
    CARRIAGEWAY_BLOCKED("carriagewayBlocked"),

    /**
     * The carriageway is partially obstructed in the specified direction due to an unplanned event.
     * 
     */
    
    CARRIAGEWAY_PARTIALLY_OBSTRUCTED("carriagewayPartiallyObstructed"),

    /**
     * Traffic in the specified direction is required to deviate from the normal lane(s) due to an unplanned event (e.g. via hard shoulder).
     * 
     */
    
    LANE_DEVIATED("laneDeviated"),

    /**
     * One or more lanes is totally obstructed in the specified direction due to an unplanned event.
     * 
     */
    
    LANES_BLOCKED("lanesBlocked"),

    /**
     * One or more lanes is partially obstructed in the specified direction due to an unplanned event.
     * 
     */
    
    LANES_PARTIALLY_OBSTRUCTED("lanesPartiallyObstructed"),

    /**
     * The road is totally obstructed, for all vehicles in both directions, due to an unplanned event.
     * 
     */
    
    ROAD_BLOCKED("roadBlocked"),

    /**
     * The road is partially obstructed in both directions due to an unplanned event.
     * 
     */
    
    ROAD_PARTIALLY_OBSTRUCTED("roadPartiallyObstructed");
    private final String value;

    TrafficRestrictionTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TrafficRestrictionTypeEnum fromValue(String v) {
        for (TrafficRestrictionTypeEnum c: TrafficRestrictionTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
