//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package eu.datex2.schema._1_0._1_0;

public enum ValidityStatusEnum {


    /**
     * The described event, action or item is currently active regardless of the definition of the validity time specification.
     * 
     */
    
    ACTIVE("active"),

    /**
     * The described event, action or item is currently suspended, that is inactive, regardless of the definition of the validity time specification.
     * 
     */
    
    SUSPENDED("suspended"),

    /**
     * The validity status of the described event, action or item is in accordance with the definition of the validity time specification.
     * 
     */
    
    DEFINED_BY_VALIDITY_TIME_SPEC("definedByValidityTimeSpec");
    private final String value;

    ValidityStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ValidityStatusEnum fromValue(String v) {
        for (ValidityStatusEnum c: ValidityStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
