//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package eu.datex2.schema._1_0._1_0;

public enum WeekOfMonthEnum {


    /**
     * First week of the month.
     * 
     */
    
    FIRST_WEEK_OF_MONTH("firstWeekOfMonth"),

    /**
     * Second week of the month.
     * 
     */
    
    SECOND_WEEK_OF_MONTH("secondWeekOfMonth"),

    /**
     * Third week of the month.
     * 
     */
    
    THIRD_WEEK_OF_MONTH("thirdWeekOfMonth"),

    /**
     * Fourth week of the month.
     * 
     */
    
    FOUTH_WEEK_OF_MONTH("fouthWeekOfMonth"),

    /**
     * Fifth week of the month (at most only 3 days and non in February when not a leap year). 
     * 
     */
    
    FIFTH_WEEK_OF_MONTH("fifthWeekOfMonth");
    private final String value;

    WeekOfMonthEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WeekOfMonthEnum fromValue(String v) {
        for (WeekOfMonthEnum c: WeekOfMonthEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
