//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum AccommodationFacilityEnumeration {

    
    UNKNOWN("unknown"),
    
    PTI_23_3("pti23_3"),
    
    SLEEPER("sleeper"),
    
    PTI_23_4("pti23_4"),
    
    COUCHETTE("couchette"),
    
    PTI_23_5("pti23_5"),
    
    SPECIAL_SEATING("specialSeating"),
    
    PTI_23_11("pti23_11"),
    
    FREE_SEATING("freeSeating"),
    
    PTI_23_12("pti23_12"),
    
    RECLINING_SEATS("recliningSeats"),
    
    PTI_23_13("pti23_13"),
    
    BABY_COMPARTMENT("babyCompartment"),
    
    FAMILY_CARRIAGE("familyCarriage");
    private final String value;

    AccommodationFacilityEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AccommodationFacilityEnumeration fromValue(String v) {
        for (AccommodationFacilityEnumeration c: AccommodationFacilityEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
