//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

import java.util.ArrayList;
import java.util.List;
public class AffectedRoute {

    
    protected RouteRef routeRef;
    
    protected List<Direction> direction;
    
    protected AffectedRoute.Sections sections;
    
    protected AffectedRoute.RouteLinks routeLinks;
    
    protected Extensions extensions;

    /**
     * Gets the value of the routeRef property.
     * 
     * @return
     *     possible object is
     *     {@link RouteRef }
     *     
     */
    public RouteRef getRouteRef() {
        return routeRef;
    }

    /**
     * Sets the value of the routeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteRef }
     *     
     */
    public void setRouteRef(RouteRef value) {
        this.routeRef = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the direction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDirection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Direction }
     * 
     * 
     */
    public List<Direction> getDirection() {
        if (direction == null) {
            direction = new ArrayList<Direction>();
        }
        return this.direction;
    }

    /**
     * Gets the value of the sections property.
     * 
     * @return
     *     possible object is
     *     {@link AffectedRoute.Sections }
     *     
     */
    public AffectedRoute.Sections getSections() {
        return sections;
    }

    /**
     * Sets the value of the sections property.
     * 
     * @param value
     *     allowed object is
     *     {@link AffectedRoute.Sections }
     *     
     */
    public void setSections(AffectedRoute.Sections value) {
        this.sections = value;
    }

    /**
     * Gets the value of the routeLinks property.
     * 
     * @return
     *     possible object is
     *     {@link AffectedRoute.RouteLinks }
     *     
     */
    public AffectedRoute.RouteLinks getRouteLinks() {
        return routeLinks;
    }

    /**
     * Sets the value of the routeLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link AffectedRoute.RouteLinks }
     *     
     */
    public void setRouteLinks(AffectedRoute.RouteLinks value) {
        this.routeLinks = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }


      public static class RouteLinks {

  
        protected List<RouteLinkRef> routeLinkRef;

        /**
         * Gets the value of the routeLinkRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the routeLinkRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRouteLinkRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RouteLinkRef }
         * 
         * 
         */
        public List<RouteLinkRef> getRouteLinkRef() {
            if (routeLinkRef == null) {
                routeLinkRef = new ArrayList<RouteLinkRef>();
            }
            return this.routeLinkRef;
        }

    }


    public static class Sections {


        protected List<AffectedSection> affectedSection;

        /**
         * Gets the value of the affectedSection property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the affectedSection property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAffectedSection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AffectedSection }
         * 
         * 
         */
        public List<AffectedSection> getAffectedSection() {
            if (affectedSection == null) {
                affectedSection = new ArrayList<AffectedSection>();
            }
            return this.affectedSection;
        }

    }

}
