//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

import java.util.ArrayList;
import java.util.List;

import uk.org.ifopt.ifopt.NavigationPathRef;
import uk.org.ifopt.ifopt.StopPlaceRef;
import uk.org.ifopt.ifopt.StopPlaceTypeEnumeration;

public class AffectedStopPlace extends AffectedStopPlaceElement {

	protected StopPlaceRef stopPlaceRef;

	protected NaturalLanguageString placeName;

	protected StopPlaceTypeEnumeration stopPlaceType;

	protected AffectedStopPlace.AffectedComponents affectedComponents;

	protected AffectedStopPlace.AffectedNavigationPaths affectedNavigationPaths;

	protected Extensions extensions;

	/**
	 * Gets the value of the stopPlaceRef property.
	 * 
	 * @return possible object is {@link StopPlaceRef }
	 * 
	 */
	public StopPlaceRef getStopPlaceRef() {
		return stopPlaceRef;
	}

	/**
	 * Sets the value of the stopPlaceRef property.
	 * 
	 * @param value
	 *            allowed object is {@link StopPlaceRef }
	 * 
	 */
	public void setStopPlaceRef(StopPlaceRef value) {
		this.stopPlaceRef = value;
	}

	/**
	 * Gets the value of the placeName property.
	 * 
	 * @return possible object is {@link NaturalLanguageString }
	 * 
	 */
	public NaturalLanguageString getPlaceName() {
		return placeName;
	}

	/**
	 * Sets the value of the placeName property.
	 * 
	 * @param value
	 *            allowed object is {@link NaturalLanguageString }
	 * 
	 */
	public void setPlaceName(NaturalLanguageString value) {
		this.placeName = value;
	}

	/**
	 * Gets the value of the stopPlaceType property.
	 * 
	 * @return possible object is {@link StopPlaceTypeEnumeration }
	 * 
	 */
	public StopPlaceTypeEnumeration getStopPlaceType() {
		return stopPlaceType;
	}

	/**
	 * Sets the value of the stopPlaceType property.
	 * 
	 * @param value
	 *            allowed object is {@link StopPlaceTypeEnumeration }
	 * 
	 */
	public void setStopPlaceType(StopPlaceTypeEnumeration value) {
		this.stopPlaceType = value;
	}

	/**
	 * Gets the value of the affectedComponents property.
	 * 
	 * @return possible object is {@link AffectedStopPlace.AffectedComponents }
	 * 
	 */
	public AffectedStopPlace.AffectedComponents getAffectedComponents() {
		return affectedComponents;
	}

	/**
	 * Sets the value of the affectedComponents property.
	 * 
	 * @param value
	 *            allowed object is {@link AffectedStopPlace.AffectedComponents }
	 * 
	 */
	public void setAffectedComponents(AffectedStopPlace.AffectedComponents value) {
		this.affectedComponents = value;
	}

	/**
	 * Gets the value of the affectedNavigationPaths property.
	 * 
	 * @return possible object is
	 *         {@link AffectedStopPlace.AffectedNavigationPaths }
	 * 
	 */
	public AffectedStopPlace.AffectedNavigationPaths getAffectedNavigationPaths() {
		return affectedNavigationPaths;
	}

	/**
	 * Sets the value of the affectedNavigationPaths property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link AffectedStopPlace.AffectedNavigationPaths }
	 * 
	 */
	public void setAffectedNavigationPaths(
			AffectedStopPlace.AffectedNavigationPaths value) {
		this.affectedNavigationPaths = value;
	}

	/**
	 * Gets the value of the extensions property.
	 * 
	 * @return possible object is {@link Extensions }
	 * 
	 */
	public Extensions getExtensions() {
		return extensions;
	}

	/**
	 * Sets the value of the extensions property.
	 * 
	 * @param value
	 *            allowed object is {@link Extensions }
	 * 
	 */
	public void setExtensions(Extensions value) {
		this.extensions = value;
	}

	
	public static class AffectedComponents {

	
		protected List<AffectedStopPlaceComponent> affectedComponent;

		/**
		 * Gets the value of the affectedComponent property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the affectedComponent property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getAffectedComponent().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link AffectedStopPlaceComponent }
		 * 
		 * 
		 */
		public List<AffectedStopPlaceComponent> getAffectedComponent() {
			if (affectedComponent == null) {
				affectedComponent = new ArrayList<AffectedStopPlaceComponent>();
			}
			return this.affectedComponent;
		}

	}

	
	public static class AffectedNavigationPaths {

	
		protected List<NavigationPathRef> navigationPathRef;

		/**
		 * Gets the value of the navigationPathRef property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the navigationPathRef property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getNavigationPathRef().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link NavigationPathRef }
		 * 
		 * 
		 */
		public List<NavigationPathRef> getNavigationPathRef() {
			if (navigationPathRef == null) {
				navigationPathRef = new ArrayList<NavigationPathRef>();
			}
			return this.navigationPathRef;
		}

	}

}
