//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

import java.util.ArrayList;
import java.util.List;
import uk.org.ifopt.acsb.AccessibilityAssessment;

public class AffectedStopPoint {


	protected String stopPointRef;

	protected String privateRef;

	protected NaturalLanguageString stopPointName;

	protected StopPointTypeEnumeration stopPointType;

	protected Location location;

	protected AffectedModes affectedModes;

	protected ZoneRef placeRef;

	protected NaturalLanguageString placeName;

	protected AccessibilityAssessment accessibilityAssessment;

	protected AffectedStopPoint.ConnectionLinks connectionLinks;

	protected Extensions extensions;

	/**
	 * Gets the value of the stopPointRef property.
	 * 
	 * @return possible object is {@link StopPointRef }
	 * 
	 */
	public String getStopPointRef() {
		return stopPointRef;
	}

	/**
	 * Sets the value of the stopPointRef property.
	 * 
	 * @param value
	 *            allowed object is {@link StopPointRef }
	 * 
	 */
	public void setStopPointRef(String value) {
		this.stopPointRef = value;
	}

	/**
	 * Gets the value of the privateRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPrivateRef() {
		return privateRef;
	}

	/**
	 * Sets the value of the privateRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPrivateRef(String value) {
		this.privateRef = value;
	}

	/**
	 * Gets the value of the stopPointName property.
	 * 
	 * @return possible object is {@link NaturalLanguageString }
	 * 
	 */
	public NaturalLanguageString getStopPointName() {
		return stopPointName;
	}

	/**
	 * Sets the value of the stopPointName property.
	 * 
	 * @param value
	 *            allowed object is {@link NaturalLanguageString }
	 * 
	 */
	public void setStopPointName(NaturalLanguageString value) {
		this.stopPointName = value;
	}

	/**
	 * Gets the value of the stopPointType property.
	 * 
	 * @return possible object is {@link StopPointTypeEnumeration }
	 * 
	 */
	public StopPointTypeEnumeration getStopPointType() {
		return stopPointType;
	}

	/**
	 * Sets the value of the stopPointType property.
	 * 
	 * @param value
	 *            allowed object is {@link StopPointTypeEnumeration }
	 * 
	 */
	public void setStopPointType(StopPointTypeEnumeration value) {
		this.stopPointType = value;
	}

	/**
	 * Gets the value of the location property.
	 * 
	 * @return possible object is {@link Location }
	 * 
	 */
	public Location getLocation() {
		return location;
	}

	/**
	 * Sets the value of the location property.
	 * 
	 * @param value
	 *            allowed object is {@link Location }
	 * 
	 */
	public void setLocation(Location value) {
		this.location = value;
	}

	/**
	 * Gets the value of the affectedModes property.
	 * 
	 * @return possible object is {@link AffectedModes }
	 * 
	 */
	public AffectedModes getAffectedModes() {
		return affectedModes;
	}

	/**
	 * Sets the value of the affectedModes property.
	 * 
	 * @param value
	 *            allowed object is {@link AffectedModes }
	 * 
	 */
	public void setAffectedModes(AffectedModes value) {
		this.affectedModes = value;
	}

	/**
	 * Gets the value of the placeRef property.
	 * 
	 * @return possible object is {@link ZoneRef }
	 * 
	 */
	public ZoneRef getPlaceRef() {
		return placeRef;
	}

	/**
	 * Sets the value of the placeRef property.
	 * 
	 * @param value
	 *            allowed object is {@link ZoneRef }
	 * 
	 */
	public void setPlaceRef(ZoneRef value) {
		this.placeRef = value;
	}

	/**
	 * Gets the value of the placeName property.
	 * 
	 * @return possible object is {@link NaturalLanguageString }
	 * 
	 */
	public NaturalLanguageString getPlaceName() {
		return placeName;
	}

	/**
	 * Sets the value of the placeName property.
	 * 
	 * @param value
	 *            allowed object is {@link NaturalLanguageString }
	 * 
	 */
	public void setPlaceName(NaturalLanguageString value) {
		this.placeName = value;
	}

	/**
	 * Gets the value of the accessibilityAssessment property.
	 * 
	 * @return possible object is {@link AccessibilityAssessment }
	 * 
	 */
	public AccessibilityAssessment getAccessibilityAssessment() {
		return accessibilityAssessment;
	}

	/**
	 * Sets the value of the accessibilityAssessment property.
	 * 
	 * @param value
	 *            allowed object is {@link AccessibilityAssessment }
	 * 
	 */
	public void setAccessibilityAssessment(AccessibilityAssessment value) {
		this.accessibilityAssessment = value;
	}

	/**
	 * Gets the value of the connectionLinks property.
	 * 
	 * @return possible object is {@link AffectedStopPoint.ConnectionLinks }
	 * 
	 */
	public AffectedStopPoint.ConnectionLinks getConnectionLinks() {
		return connectionLinks;
	}

	/**
	 * Sets the value of the connectionLinks property.
	 * 
	 * @param value
	 *            allowed object is {@link AffectedStopPoint.ConnectionLinks }
	 * 
	 */
	public void setConnectionLinks(AffectedStopPoint.ConnectionLinks value) {
		this.connectionLinks = value;
	}

	/**
	 * Gets the value of the extensions property.
	 * 
	 * @return possible object is {@link Extensions }
	 * 
	 */
	public Extensions getExtensions() {
		return extensions;
	}

	/**
	 * Sets the value of the extensions property.
	 * 
	 * @param value
	 *            allowed object is {@link Extensions }
	 * 
	 */
	public void setExtensions(Extensions value) {
		this.extensions = value;
	}


	public static class ConnectionLinks {

		
		protected List<AffectedConnectionLink> affectedConnectionLink;

		/**
		 * Gets the value of the affectedConnectionLink property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the affectedConnectionLink property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getAffectedConnectionLink().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link AffectedConnectionLink }
		 * 
		 * 
		 */
		public List<AffectedConnectionLink> getAffectedConnectionLink() {
			if (affectedConnectionLink == null) {
				affectedConnectionLink = new ArrayList<AffectedConnectionLink>();
			}
			return this.affectedConnectionLink;
		}

	}

}
