//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

import eu.datex2.schema._1_0._1_0.ReferencePointLinear;
import uk.org.ifopt.ifopt.LinkProjection;


public class AffectedRoad {


    protected ReferencePointLinear road;

    protected LinkProjection linkProjection;

    protected Offset offset;

    /**
     * Gets the value of the road property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencePointLinear }
     *     
     */
    public ReferencePointLinear getRoad() {
        return road;
    }

    /**
     * Sets the value of the road property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencePointLinear }
     *     
     */
    public void setRoad(ReferencePointLinear value) {
        this.road = value;
    }

    /**
     * Gets the value of the linkProjection property.
     * 
     * @return
     *     possible object is
     *     {@link LinkProjection }
     *     
     */
    public LinkProjection getLinkProjection() {
        return linkProjection;
    }

    /**
     * Sets the value of the linkProjection property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkProjection }
     *     
     */
    public void setLinkProjection(LinkProjection value) {
        this.linkProjection = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Offset }
     *     
     */
    public Offset getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Offset }
     *     
     */
    public void setOffset(Offset value) {
        this.offset = value;
    }

}
