//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

import uk.org.ifopt.ifopt.LinkProjection;

public class AffectedSection {


    protected SectionRef sectionRef;

    protected LinkProjection linkProjection;

    protected Offset offset;

    protected Extensions extensions;

    /**
     * Gets the value of the sectionRef property.
     * 
     * @return
     *     possible object is
     *     {@link SectionRef }
     *     
     */
    public SectionRef getSectionRef() {
        return sectionRef;
    }

    /**
     * Sets the value of the sectionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SectionRef }
     *     
     */
    public void setSectionRef(SectionRef value) {
        this.sectionRef = value;
    }

    /**
     * Gets the value of the linkProjection property.
     * 
     * @return
     *     possible object is
     *     {@link LinkProjection }
     *     
     */
    public LinkProjection getLinkProjection() {
        return linkProjection;
    }

    /**
     * Sets the value of the linkProjection property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkProjection }
     *     
     */
    public void setLinkProjection(LinkProjection value) {
        this.linkProjection = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Offset }
     *     
     */
    public Offset getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Offset }
     *     
     */
    public void setOffset(Offset value) {
        this.offset = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

}
