//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

import uk.org.ifopt.ifopt.LinkProjection;
import uk.org.ifopt.ifopt.PointProjection;
import uk.org.ifopt.ifopt.StopPlaceComponentRef;
import uk.org.ifopt.ifopt.StopPlaceComponentTypeEnumeration;
import uk.org.ifopt.ifopt.ZoneProjection;

public class AffectedStopPlaceComponent extends AffectedStopPlaceElement {

	
	protected StopPlaceComponentRef componentRef;
	
	protected NaturalLanguageString componentName;
	
	protected StopPlaceComponentTypeEnumeration componentType;
	
	protected PointProjection pointProjection;
	
	protected LinkProjection linkProjection;
	
	protected ZoneProjection zoneProjection;
	
	protected Offset offset;
	
	protected Extensions extensions;

	/**
	 * Gets the value of the componentRef property.
	 * 
	 * @return possible object is {@link StopPlaceComponentRef }
	 * 
	 */
	public StopPlaceComponentRef getComponentRef() {
		return componentRef;
	}

	/**
	 * Sets the value of the componentRef property.
	 * 
	 * @param value
	 *            allowed object is {@link StopPlaceComponentRef }
	 * 
	 */
	public void setComponentRef(StopPlaceComponentRef value) {
		this.componentRef = value;
	}

	/**
	 * Gets the value of the componentName property.
	 * 
	 * @return possible object is {@link NaturalLanguageString }
	 * 
	 */
	public NaturalLanguageString getComponentName() {
		return componentName;
	}

	/**
	 * Sets the value of the componentName property.
	 * 
	 * @param value
	 *            allowed object is {@link NaturalLanguageString }
	 * 
	 */
	public void setComponentName(NaturalLanguageString value) {
		this.componentName = value;
	}

	/**
	 * Gets the value of the componentType property.
	 * 
	 * @return possible object is {@link StopPlaceComponentTypeEnumeration }
	 * 
	 */
	public StopPlaceComponentTypeEnumeration getComponentType() {
		return componentType;
	}

	/**
	 * Sets the value of the componentType property.
	 * 
	 * @param value
	 *            allowed object is {@link StopPlaceComponentTypeEnumeration }
	 * 
	 */
	public void setComponentType(StopPlaceComponentTypeEnumeration value) {
		this.componentType = value;
	}

	/**
	 * Gets the value of the pointProjection property.
	 * 
	 * @return possible object is {@link PointProjection }
	 * 
	 */
	public PointProjection getPointProjection() {
		return pointProjection;
	}

	/**
	 * Sets the value of the pointProjection property.
	 * 
	 * @param value
	 *            allowed object is {@link PointProjection }
	 * 
	 */
	public void setPointProjection(PointProjection value) {
		this.pointProjection = value;
	}

	/**
	 * Gets the value of the linkProjection property.
	 * 
	 * @return possible object is {@link LinkProjection }
	 * 
	 */
	public LinkProjection getLinkProjection() {
		return linkProjection;
	}

	/**
	 * Sets the value of the linkProjection property.
	 * 
	 * @param value
	 *            allowed object is {@link LinkProjection }
	 * 
	 */
	public void setLinkProjection(LinkProjection value) {
		this.linkProjection = value;
	}

	/**
	 * Gets the value of the zoneProjection property.
	 * 
	 * @return possible object is {@link ZoneProjection }
	 * 
	 */
	public ZoneProjection getZoneProjection() {
		return zoneProjection;
	}

	/**
	 * Sets the value of the zoneProjection property.
	 * 
	 * @param value
	 *            allowed object is {@link ZoneProjection }
	 * 
	 */
	public void setZoneProjection(ZoneProjection value) {
		this.zoneProjection = value;
	}

	/**
	 * Gets the value of the offset property.
	 * 
	 * @return possible object is {@link Offset }
	 * 
	 */
	public Offset getOffset() {
		return offset;
	}

	/**
	 * Sets the value of the offset property.
	 * 
	 * @param value
	 *            allowed object is {@link Offset }
	 * 
	 */
	public void setOffset(Offset value) {
		this.offset = value;
	}

	/**
	 * Gets the value of the extensions property.
	 * 
	 * @return possible object is {@link Extensions }
	 * 
	 */
	public Extensions getExtensions() {
		return extensions;
	}

	/**
	 * Sets the value of the extensions property.
	 * 
	 * @param value
	 *            allowed object is {@link Extensions }
	 * 
	 */
	public void setExtensions(Extensions value) {
		this.extensions = value;
	}

}
