//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;

import uk.org.siri.xml.datatype.Duration;

public class AffectedCall extends AffectedStopPoint {

	protected BigInteger order;
	
	protected RoutePointTypeEnumeration callCondition;
	
	protected Boolean vehicleAtStop;
	
	protected Location vehicleLocationAtStop;
	protected Date aimedArrivalTime;
	protected Date actualArrivalTime;
	protected Date expectedArrivalTime;
	
	protected ProgressStatusEnumeration arrivalStatus;
	
	protected NaturalLanguageString arrivalPlatformName;
	
	protected ArrivalBoardingActivityEnumeration arrivalBoardingActivity;
	protected Date aimedDepartureTime;
	protected Date actualDepartureTime;
	protected Date expectedDepartureTime;
	
	protected ProgressStatusEnumeration departureStatus;
	
	protected NaturalLanguageString departurePlatformName;
	
	protected DepartureBoardingActivityEnumeration departureBoardingActivity;
	
	protected Duration aimedHeadwayInterval;
	
	protected Duration expectedHeadwayInterval;
	
	protected List<AffectedInterchange> affectedInterchange;

	/**
	 * Gets the value of the order property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getOrder() {
		return order;
	}

	/**
	 * Sets the value of the order property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setOrder(BigInteger value) {
		this.order = value;
	}

	/**
	 * Gets the value of the callCondition property.
	 * 
	 * @return possible object is {@link RoutePointTypeEnumeration }
	 * 
	 */
	public RoutePointTypeEnumeration getCallCondition() {
		return callCondition;
	}

	/**
	 * Sets the value of the callCondition property.
	 * 
	 * @param value
	 *            allowed object is {@link RoutePointTypeEnumeration }
	 * 
	 */
	public void setCallCondition(RoutePointTypeEnumeration value) {
		this.callCondition = value;
	}

	/**
	 * Gets the value of the vehicleAtStop property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isVehicleAtStop() {
		return vehicleAtStop;
	}

	/**
	 * Sets the value of the vehicleAtStop property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setVehicleAtStop(Boolean value) {
		this.vehicleAtStop = value;
	}

	/**
	 * Gets the value of the vehicleLocationAtStop property.
	 * 
	 * @return possible object is {@link Location }
	 * 
	 */
	public Location getVehicleLocationAtStop() {
		return vehicleLocationAtStop;
	}

	/**
	 * Sets the value of the vehicleLocationAtStop property.
	 * 
	 * @param value
	 *            allowed object is {@link Location }
	 * 
	 */
	public void setVehicleLocationAtStop(Location value) {
		this.vehicleLocationAtStop = value;
	}

	/**
	 * Gets the value of the aimedArrivalTime property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getAimedArrivalTime() {
		return aimedArrivalTime;
	}

	/**
	 * Sets the value of the aimedArrivalTime property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setAimedArrivalTime(Date value) {
		this.aimedArrivalTime = value;
	}

	/**
	 * Gets the value of the actualArrivalTime property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getActualArrivalTime() {
		return actualArrivalTime;
	}

	/**
	 * Sets the value of the actualArrivalTime property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setActualArrivalTime(Date value) {
		this.actualArrivalTime = value;
	}

	/**
	 * Gets the value of the expectedArrivalTime property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getExpectedArrivalTime() {
		return expectedArrivalTime;
	}

	/**
	 * Sets the value of the expectedArrivalTime property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setExpectedArrivalTime(Date value) {
		this.expectedArrivalTime = value;
	}

	/**
	 * Gets the value of the arrivalStatus property.
	 * 
	 * @return possible object is {@link ProgressStatusEnumeration }
	 * 
	 */
	public ProgressStatusEnumeration getArrivalStatus() {
		return arrivalStatus;
	}

	/**
	 * Sets the value of the arrivalStatus property.
	 * 
	 * @param value
	 *            allowed object is {@link ProgressStatusEnumeration }
	 * 
	 */
	public void setArrivalStatus(ProgressStatusEnumeration value) {
		this.arrivalStatus = value;
	}

	/**
	 * Gets the value of the arrivalPlatformName property.
	 * 
	 * @return possible object is {@link NaturalLanguageString }
	 * 
	 */
	public NaturalLanguageString getArrivalPlatformName() {
		return arrivalPlatformName;
	}

	/**
	 * Sets the value of the arrivalPlatformName property.
	 * 
	 * @param value
	 *            allowed object is {@link NaturalLanguageString }
	 * 
	 */
	public void setArrivalPlatformName(NaturalLanguageString value) {
		this.arrivalPlatformName = value;
	}

	/**
	 * Gets the value of the arrivalBoardingActivity property.
	 * 
	 * @return possible object is {@link ArrivalBoardingActivityEnumeration }
	 * 
	 */
	public ArrivalBoardingActivityEnumeration getArrivalBoardingActivity() {
		return arrivalBoardingActivity;
	}

	/**
	 * Sets the value of the arrivalBoardingActivity property.
	 * 
	 * @param value
	 *            allowed object is {@link ArrivalBoardingActivityEnumeration }
	 * 
	 */
	public void setArrivalBoardingActivity(
			ArrivalBoardingActivityEnumeration value) {
		this.arrivalBoardingActivity = value;
	}

	/**
	 * Gets the value of the aimedDepartureTime property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getAimedDepartureTime() {
		return aimedDepartureTime;
	}

	/**
	 * Sets the value of the aimedDepartureTime property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setAimedDepartureTime(Date value) {
		this.aimedDepartureTime = value;
	}

	/**
	 * Gets the value of the actualDepartureTime property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getActualDepartureTime() {
		return actualDepartureTime;
	}

	/**
	 * Sets the value of the actualDepartureTime property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setActualDepartureTime(Date value) {
		this.actualDepartureTime = value;
	}

	/**
	 * Gets the value of the expectedDepartureTime property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getExpectedDepartureTime() {
		return expectedDepartureTime;
	}

	/**
	 * Sets the value of the expectedDepartureTime property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setExpectedDepartureTime(Date value) {
		this.expectedDepartureTime = value;
	}

	/**
	 * Gets the value of the departureStatus property.
	 * 
	 * @return possible object is {@link ProgressStatusEnumeration }
	 * 
	 */
	public ProgressStatusEnumeration getDepartureStatus() {
		return departureStatus;
	}

	/**
	 * Sets the value of the departureStatus property.
	 * 
	 * @param value
	 *            allowed object is {@link ProgressStatusEnumeration }
	 * 
	 */
	public void setDepartureStatus(ProgressStatusEnumeration value) {
		this.departureStatus = value;
	}

	/**
	 * Gets the value of the departurePlatformName property.
	 * 
	 * @return possible object is {@link NaturalLanguageString }
	 * 
	 */
	public NaturalLanguageString getDeparturePlatformName() {
		return departurePlatformName;
	}

	/**
	 * Sets the value of the departurePlatformName property.
	 * 
	 * @param value
	 *            allowed object is {@link NaturalLanguageString }
	 * 
	 */
	public void setDeparturePlatformName(NaturalLanguageString value) {
		this.departurePlatformName = value;
	}

	/**
	 * Gets the value of the departureBoardingActivity property.
	 * 
	 * @return possible object is {@link DepartureBoardingActivityEnumeration }
	 * 
	 */
	public DepartureBoardingActivityEnumeration getDepartureBoardingActivity() {
		return departureBoardingActivity;
	}

	/**
	 * Sets the value of the departureBoardingActivity property.
	 * 
	 * @param value
	 *            allowed object is {@link DepartureBoardingActivityEnumeration }
	 * 
	 */
	public void setDepartureBoardingActivity(
			DepartureBoardingActivityEnumeration value) {
		this.departureBoardingActivity = value;
	}

	/**
	 * Gets the value of the aimedHeadwayInterval property.
	 * 
	 * @return possible object is {@link Duration }
	 * 
	 */
	public Duration getAimedHeadwayInterval() {
		return aimedHeadwayInterval;
	}

	/**
	 * Sets the value of the aimedHeadwayInterval property.
	 * 
	 * @param value
	 *            allowed object is {@link Duration }
	 * 
	 */
	public void setAimedHeadwayInterval(Duration value) {
		this.aimedHeadwayInterval = value;
	}

	/**
	 * Gets the value of the expectedHeadwayInterval property.
	 * 
	 * @return possible object is {@link Duration }
	 * 
	 */
	public Duration getExpectedHeadwayInterval() {
		return expectedHeadwayInterval;
	}

	/**
	 * Sets the value of the expectedHeadwayInterval property.
	 * 
	 * @param value
	 *            allowed object is {@link Duration }
	 * 
	 */
	public void setExpectedHeadwayInterval(Duration value) {
		this.expectedHeadwayInterval = value;
	}

	/**
	 * Gets the value of the affectedInterchange property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the affectedInterchange property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAffectedInterchange().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link AffectedInterchange }
	 * 
	 * 
	 */
	public List<AffectedInterchange> getAffectedInterchange() {
		if (affectedInterchange == null) {
			affectedInterchange = new ArrayList<AffectedInterchange>();
		}
		return this.affectedInterchange;
	}

}
