//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

import java.util.ArrayList;
import java.util.List;

import eu.datex2.schema._1_0._1_0.AreaOfInterestEnum;

public class AffectsScope {

	protected AreaOfInterestEnum areaOfInterest;

	protected AffectsScope.Operators operators;

	protected AffectsScope.Networks networks;

	protected AffectsScope.StopPoints stopPoints;

	protected AffectsScope.StopPlaces stopPlaces;

	protected AffectsScope.Places places;

	protected AffectsScope.VehicleJourneys vehicleJourneys;

	protected AffectedRoads roads;

	protected Extensions extensions;

	/**
	 * Gets the value of the areaOfInterest property.
	 * 
	 * @return possible object is {@link AreaOfInterestEnum }
	 * 
	 */
	public AreaOfInterestEnum getAreaOfInterest() {
		return areaOfInterest;
	}

	/**
	 * Sets the value of the areaOfInterest property.
	 * 
	 * @param value
	 *            allowed object is {@link AreaOfInterestEnum }
	 * 
	 */
	public void setAreaOfInterest(AreaOfInterestEnum value) {
		this.areaOfInterest = value;
	}

	/**
	 * Gets the value of the operators property.
	 * 
	 * @return possible object is {@link AffectsScope.Operators }
	 * 
	 */
	public AffectsScope.Operators getOperators() {
		return operators;
	}

	/**
	 * Sets the value of the operators property.
	 * 
	 * @param value
	 *            allowed object is {@link AffectsScope.Operators }
	 * 
	 */
	public void setOperators(AffectsScope.Operators value) {
		this.operators = value;
	}

	/**
	 * Gets the value of the networks property.
	 * 
	 * @return possible object is {@link AffectsScope.Networks }
	 * 
	 */
	public AffectsScope.Networks getNetworks() {
		return networks;
	}

	/**
	 * Sets the value of the networks property.
	 * 
	 * @param value
	 *            allowed object is {@link AffectsScope.Networks }
	 * 
	 */
	public void setNetworks(AffectsScope.Networks value) {
		this.networks = value;
	}

	/**
	 * Gets the value of the stopPoints property.
	 * 
	 * @return possible object is {@link AffectsScope.StopPoints }
	 * 
	 */
	public AffectsScope.StopPoints getStopPoints() {
		return stopPoints;
	}

	/**
	 * Sets the value of the stopPoints property.
	 * 
	 * @param value
	 *            allowed object is {@link AffectsScope.StopPoints }
	 * 
	 */
	public void setStopPoints(AffectsScope.StopPoints value) {
		this.stopPoints = value;
	}

	/**
	 * Gets the value of the stopPlaces property.
	 * 
	 * @return possible object is {@link AffectsScope.StopPlaces }
	 * 
	 */
	public AffectsScope.StopPlaces getStopPlaces() {
		return stopPlaces;
	}

	/**
	 * Sets the value of the stopPlaces property.
	 * 
	 * @param value
	 *            allowed object is {@link AffectsScope.StopPlaces }
	 * 
	 */
	public void setStopPlaces(AffectsScope.StopPlaces value) {
		this.stopPlaces = value;
	}

	/**
	 * Gets the value of the places property.
	 * 
	 * @return possible object is {@link AffectsScope.Places }
	 * 
	 */
	public AffectsScope.Places getPlaces() {
		return places;
	}

	/**
	 * Sets the value of the places property.
	 * 
	 * @param value
	 *            allowed object is {@link AffectsScope.Places }
	 * 
	 */
	public void setPlaces(AffectsScope.Places value) {
		this.places = value;
	}

	/**
	 * Gets the value of the vehicleJourneys property.
	 * 
	 * @return possible object is {@link AffectsScope.VehicleJourneys }
	 * 
	 */
	public AffectsScope.VehicleJourneys getVehicleJourneys() {
		return vehicleJourneys;
	}

	/**
	 * Sets the value of the vehicleJourneys property.
	 * 
	 * @param value
	 *            allowed object is {@link AffectsScope.VehicleJourneys }
	 * 
	 */
	public void setVehicleJourneys(AffectsScope.VehicleJourneys value) {
		this.vehicleJourneys = value;
	}

	/**
	 * Gets the value of the roads property.
	 * 
	 * @return possible object is {@link AffectedRoads }
	 * 
	 */
	public AffectedRoads getRoads() {
		return roads;
	}

	/**
	 * Sets the value of the roads property.
	 * 
	 * @param value
	 *            allowed object is {@link AffectedRoads }
	 * 
	 */
	public void setRoads(AffectedRoads value) {
		this.roads = value;
	}

	/**
	 * Gets the value of the extensions property.
	 * 
	 * @return possible object is {@link Extensions }
	 * 
	 */
	public Extensions getExtensions() {
		return extensions;
	}

	/**
	 * Sets the value of the extensions property.
	 * 
	 * @param value
	 *            allowed object is {@link Extensions }
	 * 
	 */
	public void setExtensions(Extensions value) {
		this.extensions = value;
	}

	public static class Networks {

		protected List<AffectsScope.Networks.AffectedNetwork> affectedNetwork;

		public List<AffectsScope.Networks.AffectedNetwork> getAffectedNetwork() {
			return affectedNetwork;
		}

		public void setAffectedNetwork(
				List<AffectsScope.Networks.AffectedNetwork> affectedNetwork) {
			this.affectedNetwork = affectedNetwork;
		}

		public static class AffectedNetwork

		{

		}

	}

	public static class Operators {

		protected String allOperators;

		protected List<AffectedOperator> affectedOperator;

		/**
		 * Gets the value of the allOperators property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getAllOperators() {
			return allOperators;
		}

		/**
		 * Sets the value of the allOperators property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setAllOperators(String value) {
			this.allOperators = value;
		}

		public List<AffectedOperator> getAffectedOperator() {
			return affectedOperator;
		}

		public void setAffectedOperator(List<AffectedOperator> affectedOperator) {
			this.affectedOperator = affectedOperator;
		}

	}

	public static class Places {

		protected List<AffectedPlace> affectedPlace;

		public List<AffectedPlace> getAffectedPlace() {
			return affectedPlace;
		}

		public void setAffectedPlace(List<AffectedPlace> affectedPlace) {
			this.affectedPlace = affectedPlace;
		}

	}

	public static class StopPlaces {

		protected List<AffectedStopPlace> affectedStopPlace;

		public List<AffectedStopPlace> getAffectedStopPlace() {
			return affectedStopPlace;
		}

		public void setAffectedStopPlace(
				List<AffectedStopPlace> affectedStopPlace) {
			this.affectedStopPlace = affectedStopPlace;
		}
	}

	public static class StopPoints {

		protected List<AffectedStopPoint> affectedStopPoint;

		public List<AffectedStopPoint> getAffectedStopPoint() {
			return affectedStopPoint;
		}

		public void setAffectedStopPoint(
				List<AffectedStopPoint> affectedStopPoint) {
			this.affectedStopPoint = affectedStopPoint;
		}
	}

	public static class VehicleJourneys {

		protected List<AffectedVehicleJourney> affectedVehicleJourney;

		public List<AffectedVehicleJourney> getAffectedVehicleJourney() {
			return affectedVehicleJourney;
		}
		
		public void setAffectedVehicleJourney(
				List<AffectedVehicleJourney> affectedVehicleJourney) {
			this.affectedVehicleJourney = affectedVehicleJourney;
		}
	}

}
