//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

import java.util.ArrayList;
import java.util.List;
import uk.org.ifopt.ifopt.AccessModesEnumeration;
public class AffectedModes {


    protected String allModes;

    protected List<AffectedModes.Mode> mode;

    /**
     * Gets the value of the allModes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllModes() {
        return allModes;
    }

    /**
     * Sets the value of the allModes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllModes(String value) {
        this.allModes = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AffectedModes.Mode }
     * 
     * 
     */
    public List<AffectedModes.Mode> getMode() {
        if (mode == null) {
            mode = new ArrayList<AffectedModes.Mode>();
        }
        return this.mode;
    }


   
    public static class Mode {

   
        protected VehicleModesOfTransportEnumeration vehicleMode;
   
        protected AirSubmodesOfTransportEnumeration airSubmode;
   
        protected BusSubmodesOfTransportEnumeration busSubmode;
   
        protected CoachSubmodesOfTransportEnumeration coachSubmode;
   
        protected MetroSubmodesOfTransportEnumeration metroSubmode;
   
        protected RailSubmodesOfTransportEnumeration railSubmode;
   
        protected TramSubmodesOfTransportEnumeration tramSubmode;
   
        protected WaterSubmodesOfTransportEnumeration waterSubmode;
   
        protected AccessModesEnumeration accessMode;

        /**
         * Gets the value of the vehicleMode property.
         * 
         * @return
         *     possible object is
         *     {@link VehicleModesOfTransportEnumeration }
         *     
         */
        public VehicleModesOfTransportEnumeration getVehicleMode() {
            return vehicleMode;
        }

        /**
         * Sets the value of the vehicleMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link VehicleModesOfTransportEnumeration }
         *     
         */
        public void setVehicleMode(VehicleModesOfTransportEnumeration value) {
            this.vehicleMode = value;
        }

        /**
         * Gets the value of the airSubmode property.
         * 
         * @return
         *     possible object is
         *     {@link AirSubmodesOfTransportEnumeration }
         *     
         */
        public AirSubmodesOfTransportEnumeration getAirSubmode() {
            return airSubmode;
        }

        /**
         * Sets the value of the airSubmode property.
         * 
         * @param value
         *     allowed object is
         *     {@link AirSubmodesOfTransportEnumeration }
         *     
         */
        public void setAirSubmode(AirSubmodesOfTransportEnumeration value) {
            this.airSubmode = value;
        }

        /**
         * Gets the value of the busSubmode property.
         * 
         * @return
         *     possible object is
         *     {@link BusSubmodesOfTransportEnumeration }
         *     
         */
        public BusSubmodesOfTransportEnumeration getBusSubmode() {
            return busSubmode;
        }

        /**
         * Sets the value of the busSubmode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BusSubmodesOfTransportEnumeration }
         *     
         */
        public void setBusSubmode(BusSubmodesOfTransportEnumeration value) {
            this.busSubmode = value;
        }

        /**
         * Gets the value of the coachSubmode property.
         * 
         * @return
         *     possible object is
         *     {@link CoachSubmodesOfTransportEnumeration }
         *     
         */
        public CoachSubmodesOfTransportEnumeration getCoachSubmode() {
            return coachSubmode;
        }

        /**
         * Sets the value of the coachSubmode property.
         * 
         * @param value
         *     allowed object is
         *     {@link CoachSubmodesOfTransportEnumeration }
         *     
         */
        public void setCoachSubmode(CoachSubmodesOfTransportEnumeration value) {
            this.coachSubmode = value;
        }

        /**
         * Gets the value of the metroSubmode property.
         * 
         * @return
         *     possible object is
         *     {@link MetroSubmodesOfTransportEnumeration }
         *     
         */
        public MetroSubmodesOfTransportEnumeration getMetroSubmode() {
            return metroSubmode;
        }

        /**
         * Sets the value of the metroSubmode property.
         * 
         * @param value
         *     allowed object is
         *     {@link MetroSubmodesOfTransportEnumeration }
         *     
         */
        public void setMetroSubmode(MetroSubmodesOfTransportEnumeration value) {
            this.metroSubmode = value;
        }

        /**
         * Gets the value of the railSubmode property.
         * 
         * @return
         *     possible object is
         *     {@link RailSubmodesOfTransportEnumeration }
         *     
         */
        public RailSubmodesOfTransportEnumeration getRailSubmode() {
            return railSubmode;
        }

        /**
         * Sets the value of the railSubmode property.
         * 
         * @param value
         *     allowed object is
         *     {@link RailSubmodesOfTransportEnumeration }
         *     
         */
        public void setRailSubmode(RailSubmodesOfTransportEnumeration value) {
            this.railSubmode = value;
        }

        /**
         * Gets the value of the tramSubmode property.
         * 
         * @return
         *     possible object is
         *     {@link TramSubmodesOfTransportEnumeration }
         *     
         */
        public TramSubmodesOfTransportEnumeration getTramSubmode() {
            return tramSubmode;
        }

        /**
         * Sets the value of the tramSubmode property.
         * 
         * @param value
         *     allowed object is
         *     {@link TramSubmodesOfTransportEnumeration }
         *     
         */
        public void setTramSubmode(TramSubmodesOfTransportEnumeration value) {
            this.tramSubmode = value;
        }

        /**
         * Gets the value of the waterSubmode property.
         * 
         * @return
         *     possible object is
         *     {@link WaterSubmodesOfTransportEnumeration }
         *     
         */
        public WaterSubmodesOfTransportEnumeration getWaterSubmode() {
            return waterSubmode;
        }

        /**
         * Sets the value of the waterSubmode property.
         * 
         * @param value
         *     allowed object is
         *     {@link WaterSubmodesOfTransportEnumeration }
         *     
         */
        public void setWaterSubmode(WaterSubmodesOfTransportEnumeration value) {
            this.waterSubmode = value;
        }

        /**
         * Gets the value of the accessMode property.
         * 
         * @return
         *     possible object is
         *     {@link AccessModesEnumeration }
         *     
         */
        public AccessModesEnumeration getAccessMode() {
            return accessMode;
        }

        /**
         * Sets the value of the accessMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link AccessModesEnumeration }
         *     
         */
        public void setAccessMode(AccessModesEnumeration value) {
            this.accessMode = value;
        }

    }

}
