//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum AudienceEnumeration {

    
    PUBLIC("public"),
    
    EMERGENCY_SERVICES("emergencyServices"),
    
    STAFF("staff"),
    
    STATION_STAFF("stationStaff"),
    
    MANAGEMENT("management"),
    
    INFO_SERVICES("infoServices");
    private final String value;

    AudienceEnumeration(String v) {
        value = v;
    }

    public static AudienceEnumeration fromString(String v) {
		if (v != null) {
			for (AudienceEnumeration c : AudienceEnumeration.values()) {
				if (v.equalsIgnoreCase(c.toString())) {
			          return c;
			    }				
			}
		}
		throw new IllegalArgumentException(v);
	}

	@Override
	public String toString() {
		return value;
	}

}
