//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum CoachSubmodesOfTransportEnumeration {

    
    PTI_3_0("pti3_0"),
    
    UNKNOWN("unknown"),
    
    PTI_3_1("pti3_1"),
    
    INTERNATIONAL_COACH_SERVICE("internationalCoachService"),
    
    PTI_3_2("pti3_2"),
    
    NATIONAL_COACH_SERVICE("nationalCoachService"),
    
    PTI_3_3("pti3_3"),
    
    SHUTTLE_COACH_SERVICE("shuttleCoachService"),
    
    PTI_3_4("pti3_4"),
    
    REGIONAL_COACH_SERVICE("regionalCoachService"),
    
    PTI_3_5("pti3_5"),
    
    SPECIAL_COACH_SERVICE("specialCoachService"),
    
    PTI_3_6("pti3_6"),
    
    SIGHTSEEING_COACH_SERVICE("sightseeingCoachService"),
    
    PTI_3_7("pti3_7"),
    
    TOURIST_COACH_SERVICE("touristCoachService"),
    
    PTI_3_8("pti3_8"),
    
    COMMUTER_COACH_SERVICE("commuterCoachService"),
    
    PTI_3_9("pti3_9"),
    
    ALL_COACH_SERVICES("allCoachServices"),
    
    PTI_3_255("pti3_255"),
    
    UNDEFINED("undefined");
    private final String value;

    CoachSubmodesOfTransportEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CoachSubmodesOfTransportEnumeration fromValue(String v) {
        for (CoachSubmodesOfTransportEnumeration c: CoachSubmodesOfTransportEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
