//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum DaysOfWeekEnumerationx {

    
    UNKNOWN(DayTypeEnumeration.UNKNOWN),
    
    MONDAY(DayTypeEnumeration.MONDAY),
    
    TUESDAY(DayTypeEnumeration.TUESDAY),
    
    WEDNESDAY(DayTypeEnumeration.WEDNESDAY),
    
    THURSDAY(DayTypeEnumeration.THURSDAY),
    
    FRIDAY(DayTypeEnumeration.FRIDAY),
    
    SATURDAY(DayTypeEnumeration.SATURDAY),
    
    SUNDAY(DayTypeEnumeration.SUNDAY),
    
    MONDAY_TO_FRIDAY(DayTypeEnumeration.MONDAY_TO_FRIDAY),
    
    MONDAY_TO_SATURDAY(DayTypeEnumeration.MONDAY_TO_SATURDAY),
    
    WEEKDAYS(DayTypeEnumeration.WEEKDAYS),
    
    WEEKENDS(DayTypeEnumeration.WEEKENDS);
    private final DayTypeEnumeration value;

    DaysOfWeekEnumerationx(DayTypeEnumeration v) {
        value = v;
    }

    public DayTypeEnumeration value() {
        return value;
    }

    public static DaysOfWeekEnumerationx fromValue(DayTypeEnumeration v) {
        for (DaysOfWeekEnumerationx c: DaysOfWeekEnumerationx.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
