//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

public class DefaultedText extends NaturalLanguageString {
	
	public DefaultedText() {
		super();
	}
	
	public DefaultedText(String value){
		super(value);
	}

	protected Boolean overridden;

	/**
	 * Gets the value of the overridden property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isOverridden() {
		if (overridden == null) {
			return true;
		} else {
			return overridden;
		}
	}

	/**
	 * Sets the value of the overridden property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setOverridden(Boolean value) {
		this.overridden = value;
	}

}
