//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

import java.util.ArrayList;
import java.util.List;

import uk.org.ifopt.ifopt.EquipmentStatusEnumeration;

public class EquipmentAvailability {

  
    protected String equipmentRef;
  
    protected NaturalLanguageString description;
  
    protected String equipmentTypeRef;
  
    protected HalfOpenTimestampRange validityPeriod;
  
    protected EquipmentStatusEnumeration equipmentStatus;
  
    protected EquipmentAvailability.EquipmentFeatures equipmentFeatures;
  
    protected Extensions extensions;

    /**
     * Gets the value of the equipmentRef property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentRef }
     *     
     */
    public String getEquipmentRef() {
        return equipmentRef;
    }

    /**
     * Sets the value of the equipmentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentRef }
     *     
     */
    public void setEquipmentRef(String value) {
        this.equipmentRef = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageString }
     *     
     */
    public NaturalLanguageString getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageString }
     *     
     */
    public void setDescription(NaturalLanguageString value) {
        this.description = value;
    }

    /**
     * Gets the value of the equipmentTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentTypeRef }
     *     
     */
    public String getEquipmentTypeRef() {
        return equipmentTypeRef;
    }

    /**
     * Sets the value of the equipmentTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentTypeRef }
     *     
     */
    public void setEquipmentTypeRef(String value) {
        this.equipmentTypeRef = value;
    }

    /**
     * Gets the value of the validityPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link HalfOpenTimestampRange }
     *     
     */
    public HalfOpenTimestampRange getValidityPeriod() {
        return validityPeriod;
    }

    /**
     * Sets the value of the validityPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link HalfOpenTimestampRange }
     *     
     */
    public void setValidityPeriod(HalfOpenTimestampRange value) {
        this.validityPeriod = value;
    }

    /**
     * Gets the value of the equipmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentStatusEnumeration }
     *     
     */
    public EquipmentStatusEnumeration getEquipmentStatus() {
        return equipmentStatus;
    }

    /**
     * Sets the value of the equipmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentStatusEnumeration }
     *     
     */
    public void setEquipmentStatus(EquipmentStatusEnumeration value) {
        this.equipmentStatus = value;
    }

    /**
     * Gets the value of the equipmentFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentAvailability.EquipmentFeatures }
     *     
     */
    public EquipmentAvailability.EquipmentFeatures getEquipmentFeatures() {
        return equipmentFeatures;
    }

    /**
     * Sets the value of the equipmentFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentAvailability.EquipmentFeatures }
     *     
     */
    public void setEquipmentFeatures(EquipmentAvailability.EquipmentFeatures value) {
        this.equipmentFeatures = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

    public static class EquipmentFeatures {


        protected List<String> featureRef;

        /**
         * Gets the value of the featureRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the featureRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeatureRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureRef }
         * 
         * 
         */
        public List<String> getFeatureRef() {
            if (featureRef == null) {
                featureRef = new ArrayList<String>();
            }
            return this.featureRef;
        }

    }

}
