//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

import java.util.ArrayList;
import java.util.List;
import uk.org.ifopt.acsb.AccessibilityAssessment;
import uk.org.ifopt.acsb.Accessibility;
import uk.org.ifopt.acsb.Suitability;


public class Facility {

    protected String facilityCode;

    protected NaturalLanguageString description;

    protected List<FacilityCategoryEnumeration> facilityClass;

    protected Facility.Features features;

    protected String ownerRef;

    protected NaturalLanguageString ownerName;

    protected MonitoringValidityCondition validityCondition;

    protected FacilityLocation facilityLocation;

    protected Facility.Limitations limitations;

    protected Facility.Suitabilities suitabilities;

    protected AccessibilityAssessment accessibilityAssessment;

    protected Extensions extensions;

    /**
     * Gets the value of the facilityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityCode() {
        return facilityCode;
    }

    /**
     * Sets the value of the facilityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityCode(String value) {
        this.facilityCode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageString }
     *     
     */
    public NaturalLanguageString getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageString }
     *     
     */
    public void setDescription(NaturalLanguageString value) {
        this.description = value;
    }

    /**
     * Gets the value of the facilityClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the facilityClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFacilityClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FacilityCategoryEnumeration }
     * 
     * 
     */
    public List<FacilityCategoryEnumeration> getFacilityClass() {
        if (facilityClass == null) {
            facilityClass = new ArrayList<FacilityCategoryEnumeration>();
        }
        return this.facilityClass;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link Facility.Features }
     *     
     */
    public Facility.Features getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link Facility.Features }
     *     
     */
    public void setFeatures(Facility.Features value) {
        this.features = value;
    }

    /**
     * Gets the value of the ownerRef property.
     * 
     * @return
     *     possible object is
     *     {@link OrganisationRef }
     *     
     */
    public String getOwnerRef() {
        return ownerRef;
    }

    /**
     * Sets the value of the ownerRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganisationRef }
     *     
     */
    public void setOwnerRef(String value) {
        this.ownerRef = value;
    }

    /**
     * Gets the value of the ownerName property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageString }
     *     
     */
    public NaturalLanguageString getOwnerName() {
        return ownerName;
    }

    /**
     * Sets the value of the ownerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageString }
     *     
     */
    public void setOwnerName(NaturalLanguageString value) {
        this.ownerName = value;
    }

    /**
     * Gets the value of the validityCondition property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringValidityCondition }
     *     
     */
    public MonitoringValidityCondition getValidityCondition() {
        return validityCondition;
    }

    /**
     * Sets the value of the validityCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringValidityCondition }
     *     
     */
    public void setValidityCondition(MonitoringValidityCondition value) {
        this.validityCondition = value;
    }

    /**
     * Gets the value of the facilityLocation property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityLocation }
     *     
     */
    public FacilityLocation getFacilityLocation() {
        return facilityLocation;
    }

    /**
     * Sets the value of the facilityLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityLocation }
     *     
     */
    public void setFacilityLocation(FacilityLocation value) {
        this.facilityLocation = value;
    }

    /**
     * Gets the value of the limitations property.
     * 
     * @return
     *     possible object is
     *     {@link Facility.Limitations }
     *     
     */
    public Facility.Limitations getLimitations() {
        return limitations;
    }

    /**
     * Sets the value of the limitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Facility.Limitations }
     *     
     */
    public void setLimitations(Facility.Limitations value) {
        this.limitations = value;
    }

    /**
     * Gets the value of the suitabilities property.
     * 
     * @return
     *     possible object is
     *     {@link Facility.Suitabilities }
     *     
     */
    public Facility.Suitabilities getSuitabilities() {
        return suitabilities;
    }

    /**
     * Sets the value of the suitabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Facility.Suitabilities }
     *     
     */
    public void setSuitabilities(Facility.Suitabilities value) {
        this.suitabilities = value;
    }

    /**
     * Gets the value of the accessibilityAssessment property.
     * 
     * @return
     *     possible object is
     *     {@link AccessibilityAssessment }
     *     
     */
    public AccessibilityAssessment getAccessibilityAssessment() {
        return accessibilityAssessment;
    }

    /**
     * Sets the value of the accessibilityAssessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessibilityAssessment }
     *     
     */
    public void setAccessibilityAssessment(AccessibilityAssessment value) {
        this.accessibilityAssessment = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }


    public static class Features {
    
        protected List<AllFacilitiesFeature> feature;

        /**
         * Gets the value of the feature property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the feature property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeature().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AllFacilitiesFeature }
         * 
         * 
         */
        public List<AllFacilitiesFeature> getFeature() {
            if (feature == null) {
                feature = new ArrayList<AllFacilitiesFeature>();
            }
            return this.feature;
        }

    }
  
    public static class Limitations {


        protected Accessibility wheelchairAccess;

        protected Accessibility stepFreeAccess;

        protected Accessibility escalatorFreeAccess;

        protected Accessibility liftFreeAccess;

        protected Accessibility audibleSignalsAvailable;

        protected Accessibility visualSignsAvailable;

        /**
         * Gets the value of the wheelchairAccess property.
         * 
         * @return
         *     possible object is
         *     {@link Accessibility }
         *     
         */
        public Accessibility getWheelchairAccess() {
            return wheelchairAccess;
        }

        /**
         * Sets the value of the wheelchairAccess property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accessibility }
         *     
         */
        public void setWheelchairAccess(Accessibility value) {
            this.wheelchairAccess = value;
        }

        /**
         * Gets the value of the stepFreeAccess property.
         * 
         * @return
         *     possible object is
         *     {@link Accessibility }
         *     
         */
        public Accessibility getStepFreeAccess() {
            return stepFreeAccess;
        }

        /**
         * Sets the value of the stepFreeAccess property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accessibility }
         *     
         */
        public void setStepFreeAccess(Accessibility value) {
            this.stepFreeAccess = value;
        }

        /**
         * Gets the value of the escalatorFreeAccess property.
         * 
         * @return
         *     possible object is
         *     {@link Accessibility }
         *     
         */
        public Accessibility getEscalatorFreeAccess() {
            return escalatorFreeAccess;
        }

        /**
         * Sets the value of the escalatorFreeAccess property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accessibility }
         *     
         */
        public void setEscalatorFreeAccess(Accessibility value) {
            this.escalatorFreeAccess = value;
        }

        /**
         * Gets the value of the liftFreeAccess property.
         * 
         * @return
         *     possible object is
         *     {@link Accessibility }
         *     
         */
        public Accessibility getLiftFreeAccess() {
            return liftFreeAccess;
        }

        /**
         * Sets the value of the liftFreeAccess property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accessibility }
         *     
         */
        public void setLiftFreeAccess(Accessibility value) {
            this.liftFreeAccess = value;
        }

        /**
         * Whether a Place has Audible signals for the viusally impaired.
         * 
         * @return
         *     possible object is
         *     {@link Accessibility }
         *     
         */
        public Accessibility getAudibleSignalsAvailable() {
            return audibleSignalsAvailable;
        }

        /**
         * Sets the value of the audibleSignalsAvailable property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accessibility }
         *     
         */
        public void setAudibleSignalsAvailable(Accessibility value) {
            this.audibleSignalsAvailable = value;
        }

        /**
         * Whether a Place hasVisual signals for the hearing impaired.
         * 
         * @return
         *     possible object is
         *     {@link Accessibility }
         *     
         */
        public Accessibility getVisualSignsAvailable() {
            return visualSignsAvailable;
        }

        /**
         * Sets the value of the visualSignsAvailable property.
         * 
         * @param value
         *     allowed object is
         *     {@link Accessibility }
         *     
         */
        public void setVisualSignsAvailable(Accessibility value) {
            this.visualSignsAvailable = value;
        }

    }
 
    public static class Suitabilities {


        protected List<Suitability> suitability;

        /**
         * Gets the value of the suitability property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the suitability property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSuitability().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Suitability }
         * 
         * 
         */
        public List<Suitability> getSuitability() {
            if (suitability == null) {
                suitability = new ArrayList<Suitability>();
            }
            return this.suitability;
        }

    }

}
