//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum FacilityStatusEnumeration {

    
    UNKNOWN("unknown"),
    
    AVAILABLE("available"),
    
    NOT_AVAILABLE("notAvailable"),
    
    PARTIALLY_AVAILABLE("partiallyAvailable"),
    
    ADDED("added"),
    
    REMOVED("removed");
    private final String value;

    FacilityStatusEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FacilityStatusEnumeration fromValue(String v) {
        for (FacilityStatusEnumeration c: FacilityStatusEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
