//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum FareClassFacilityEnumeration {

    
    UNKNOWN("unknown"),
    
    PTI_23_0("pti23_0"),
    
    PTI_23_6("pti23_6"),
    
    FIRST_CLASS("firstClass"),
    
    PTI_23_7("pti23_7"),
    
    SECOND_CLASS("secondClass"),
    
    PTI_23_8("pti23_8"),
    
    THIRD_CLASS("thirdClass"),
    
    PTI_23_9("pti23_9"),
    
    ECONOMY_CLASS("economyClass"),
    
    PTI_23_10("pti23_10"),
    
    BUSINESS_CLASS("businessClass");
    private final String value;

    FareClassFacilityEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FareClassFacilityEnumeration fromValue(String v) {
        for (FareClassFacilityEnumeration c: FareClassFacilityEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
