//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public class FramedVehicleJourneyRef {


    protected String dataFrameRef;
    protected String datedVehicleJourneyRef;

    /**
     * Gets the value of the dataFrameRef property.
     * 
     * @return
     *     possible object is
     *     {@link DataFrameRef }
     *     
     */
    
    public String getDataFrameRef() {
        return dataFrameRef;
    }

    /**
     * Sets the value of the dataFrameRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataFrameRef }
     *     
     */
    
    public void setDataFrameRef(String value) {
        this.dataFrameRef = value;
    }

    /**
     * Gets the value of the datedVehicleJourneyRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    
    public String getDatedVehicleJourneyRef() {
        return datedVehicleJourneyRef;
    }

    /**
     * Sets the value of the datedVehicleJourneyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    
    public void setDatedVehicleJourneyRef(String value) {
        this.datedVehicleJourneyRef = value;
    }

}
