//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum InterchangeStatusEnumeration {

    
    PTI_31_0("pti31_0"),
    
    UNKNOWN("unknown"),
    
    PTI_31_1("pti31_1"),
    
    CONNECTION("connection"),
    
    PTI_31_2("pti31_2"),
    
    REPLACEMENT("replacement"),
    
    PTI_31_3("pti31_3"),
    
    ALTERNATIVE("alternative"),
    
    PTI_31_4("pti31_4"),
    
    CONNECTION_NOT_HELD("connectionNotHeld"),
    
    PTI_31_5("pti31_5"),
    
    CONNECTION_HELD("connectionHeld"),
    
    PTI_31_6("pti31_6"),
    
    STATUS_OF_CONENCTION_UNDECIDED("statusOfConenctionUndecided"),
    
    PTI_31_255("pti31_255"),
    
    UNDEFINED_CROSS_REFERENCE_INFORMATION("undefinedCrossReferenceInformation");
    private final String value;

    InterchangeStatusEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InterchangeStatusEnumeration fromValue(String v) {
        for (InterchangeStatusEnumeration c: InterchangeStatusEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
