//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;
public enum MiscellaneousReasonEnumeration {

    
    PTI_19_0("pti19_0"),

    /**
     * TPEG Pti_19_0   unknown
     * 
     */
    
    UNKNOWN("unknown"),
    
    PTI_19_1("pti19_1"),

    /**
     * TPEG Pti_19_1   incident
     * 
     */
    
    INCIDENT("incident"),
    
    PTI_19_1_ALIAS_1("pti19_1_Alias_1"),

    /**
     * Near Miss - alias to TPEG Pti_19_1   incident
     * 
     */
    
    NEAR_MISS("nearMiss"),
    
    PTI_19_1_ALIAS_2("pti19_1_Alias_2"),

    /**
     * Near Miss - alias to TPEG Pti_19_1   incident
     * 
     */
    
    SAFETY_VIOLATION("safetyViolation"),
    
    PTI_19_1_ALIAS_3("pti19_1_Alias_3"),

    /**
     * Signal passed at danger - alias to TPEG Pti_19_1   incident
     * 
     */
    
    SIGNAL_PASSED_AT_DANGER("signalPassedAtDanger"),
    
    PTI_19_1_ALIAS_4("pti19_1_Alias_4"),

    /**
     * Station overrun - alias to TPEG Pti_19_1   incident
     * 
     */
    
    STATION_OVERRUN("stationOverrun"),
    
    PTI_19_1_ALIAS_5("pti19_1_Alias_5"),

    /**
     * trainDoor- alias to TPEG Pti_19_1   incident
     * 
     */
    
    TRAIN_DOOR("trainDoor"),
    
    PTI_19_1_ALIAS_6("pti19_1_Alias_6"),

    /**
     * Unspecified emergency service visit. Alias to pti19
     * 
     */
    
    EMERGENCY_SERVICES_CALL("emergencyServicesCall"),
    
    PTI_19_2("pti19_2"),

    /**
     * TPEG Pti_19_2   bomb explosion
     * 
     */
    
    BOMB_EXPLOSION("bombExplosion"),
    
    PTI_19_3("pti19_3"),

    /**
     * TPEG Pti_19_3   security alert
     * 
     */
    
    SECURITY_ALERT("securityAlert"),
    
    PTI_19_3_ALIAS_1("pti19_3_Alias_1"),

    /**
     * request of the police Alias to TPEG Pti_19_3   security alert
     * 
     */
    
    POLICE_REQUEST("policeRequest"),
    
    PTI_19_3_ALIAS_2("pti19_3_Alias_2"),

    /**
     * fire brigade safety checksAlias to TPEG Pti_19_3   security alert
     * 
     */
    
    FIRE_BRIGADE_SAFETY_CHECKS("fireBrigadeSafetyChecks"),
    
    PTI_19_3_ALIAS_3("pti19_3_Alias_3"),

    /**
     * an unattended bag TPEG Pti_19_3   security alert
     * 
     */
    
    UNATTENDED_BAG("unattendedBag"),
    
    PTI_19_3_ALIAS_4("pti19_3_Alias_4"),

    /**
     * telephoned threat TPEG Pti_19_3   security alert
     * 
     */
    
    TELEPHONED_THREAT("telephonedThreat"),
    
    PTI_19_3_ALIAS_5("pti19_3_Alias_5"),

    /**
     * telephoned threat TPEG Pti_19_3   security alert
     * 
     */
    
    SUSPECT_VEHICLE("suspectVehicle"),
    
    PTI_19_3_ALIAS_6("pti19_3_Alias_6"),
    
    CIVIL_EMERGENCY("civilEmergency"),
    
    PTI_19_3_ALIAS_7("pti19_3_Alias_7"),
    
    AIR_RAID("airRaid"),
    
    PTI_19_3_ALIAS_8("pti19_3_Alias_8"),
    
    SABOTAGE("sabotage"),
    
    PTI_19_3_ALIAS_9("pti19_3_Alias_9"),
    
    BOMB_ALERT("bombAlert"),
    
    PTI_19_3_ALIAS_10("pti19_3_Alias_10"),
    
    ATTACH("attach"),
    
    PTI_19_3_ALIAS_11("pti19_3_Alias_11"),
    
    EVACUATION("evacuation"),
    
    PTI_19_3_ALIAS_12("pti19_3_Alias_12"),
    
    TERRORIST_INCIDENT("terroristIncident"),
    
    PTI_19_3_ALIAS_13("pti19_3_Alias_13"),
    
    GUNFIRE_ON_ROADWAY("gunfireOnRoadway"),
    
    PTI_19_3_ALIAS_14("pti19_3_Alias_14"),
    
    EXPLOSION("explosion"),
    
    PTI_19_3_ALIAS_15("pti19_3_Alias_15"),
    
    EXPLOSION_HAZARD("explosionHazard"),
    
    PTI_19_3_ALIAS_16("pti19_3_Alias_16"),
    
    SECURITY_INCIDENT("securityIncident"),
    
    PTI_19_4("pti19_4"),

    /**
     * TPEG Pti_19_4   fire
     * 
     */
    
    FIRE("fire"),
    
    PTI_19_4_ALIAS_1("pti19_4_Alias_1"),

    /**
     * linesideFire alias to TPEG Pti_19_4   fire
     * 
     */
    
    LINESIDE_FIRE("linesideFire"),
    
    PTI_19_5("pti19_5"),

    /**
     * TPEG Pti_19_5   vandalism
     * 
     */
    
    VANDALISM("vandalism"),
    
    PTI_19_5_ALIAS_1("pti19_5_Alias_1"),

    /**
     * passengerActionAlias to pti19
     * 
     */
    
    PASSENGER_ACTION("passengerAction"),
    
    PTI_19_5_ALIAS_2("pti19_5_Alias_2"),

    /**
     * Assault on stafft.Alias to pti19
     * 
     */
    
    STAFF_ASSAULT("staffAssault"),
    
    PTI_19_5_ALIAS_3("pti19_5_Alias_3"),

    /**
     * Railway Crime Alias to pti19
     * 
     */
    
    RAILWAY_CRIME("railwayCrime"),
    
    PTI_19_6("pti19_6"),

    /**
     * TPEG Pti_19_6   accident
     * 
     */
    
    ACCIDENT("accident"),
    
    PTI_19_6_ALIAS_1("pti19_6_Alias_1"),

    /**
     * fatality alias to TPEG Pti_19_6   accident
     * 
     */
    
    FATALITY("fatality"),
    
    PTI_19_6_ALIAS_2("pti19_6_Alias_2"),

    /**
     * a person under a train  - alias to TPEG Pti_19_6   accident
     * 
     */
    
    PERSON_UNDER_TRAIN("personUnderTrain"),
    
    PTI_19_6_ALIAS_3("pti19_6_Alias_3"),

    /**
     * a person hit by  a train  - alias to TPEG Pti_19_6   accident
     * 
     */
    
    PERSON_HIT_BY_TRAIN("personHitByTrain"),
    
    PTI_19_6_ALIAS_4("pti19_6_Alias_4"),

    /**
     * person ill On Vehicle -Alias to pti19_6
     * 
     */
    
    PERSON_ILL_ON_VEHICLE("personIllOnVehicle"),
    
    PTI_19_6_ALIAS_5("pti19_6_Alias_5"),

    /**
     * emergencyServices - alias to TPEG Pti_19_6   accident
     * 
     */
    
    EMERGENCY_SERVICES("emergencyServices"),
    
    PTI_19_6_ALIAS_6("pti19_6_Alias_6"),

    /**
     * Collision - Alias to pti19_6
     * 
     */
    
    COLLISION("collision"),
    
    PTI_19_7("pti19_7"),

    /**
     * TPEG Pti_19_7   overcrowded
     * 
     */
    
    OVERCROWDED("overcrowded"),
    
    PTI_19_8("pti19_8"),

    /**
     * TPEG Pti_19_8   insufficient demand
     * 
     */
    
    INSUFFICIENT_DEMAND("insufficientDemand"),
    
    PTI_19_9("pti19_9"),

    /**
     * TPEG Pti_19_9   lighting failure
     * 
     */
    
    LIGHTING_FAILURE("lightingFailure"),
    
    PTI_19_10("pti19_10"),

    /**
     * TPEG Pti_19_10  leader board failure
     * 
     */
    
    LEADER_BOARD_FAILURE("leaderBoardFailure"),
    
    PTI_19_11("pti19_11"),

    /**
     * TPEG Pti_19_11  service indicator failure
     * 
     */
    
    SERVICE_INDICATOR_FAILURE("serviceIndicatorFailure"),
    
    PTI_19_12("pti19_12"),

    /**
     * TPEG Pti_19_12  service failure
     * 
     */
    
    SERVICE_FAILURE("serviceFailure"),
    
    PTI_19_13("pti19_13"),

    /**
     * TPEG Pti_19_13  operator ceased trading
     * 
     */
    
    OPERATOR_CEASED_TRADING("operatorCeasedTrading"),
    
    PTI_19_14("pti19_14"),

    /**
     * TPEG Pti_19_14  operator suspended
     * 
     */
    
    OPERATOR_SUSPENDED("operatorSuspended"),
    
    PTI_19_15("pti19_15"),

    /**
     * TPEG Pti_19_15  congestion
     * 
     */
    
    CONGESTION("congestion"),
    
    PTI_19_16("pti19_16"),

    /**
     * TPEG Pti_19_16  route blockage
     * 
     */
    
    ROUTE_BLOCKAGE("routeBlockage"),
    
    PTI_19_17("pti19_17"),

    /**
     * TPEG Pti_19_17  person on the line
     * 
     */
    
    PERSON_ON_THE_LINE("personOnTheLine"),
    
    PTI_19_18("pti19_18"),

    /**
     * TPEG Pti_19_18  vehicle on the line
     * 
     */
    
    VEHICLE_ON_THE_LINE("vehicleOnTheLine"),
    
    PTI_19_18_ALIAS_1("pti19_18_Alias_1"),

    /**
     * Level Crossing Incident - alias to TPEG Pti_19_18  vehicle on the line
     * 
     */
    
    LEVEL_CROSSING_INCIDENT("levelCrossingIncident"),
    
    PTI_19_19("pti19_19"),

    /**
     * TPEG Pti_19_19  object on the line
     * 
     */
    
    OBJECT_ON_THE_LINE("objectOnTheLine"),
    
    PTI_19_19_ALIAS_1("pti19_19_Alias_1"),

    /**
     * fallen tree on line- alias to TPEG Pti_19_19  object on the line
     * 
     */
    
    FALLEN_TREE_ON_THE_LINE("fallenTreeOnTheLine"),
    
    PTI_19_19_ALIAS_2("pti19_19_Alias_2"),

    /**
     * vegetation -  alias to TPEG Pti_19_19  object on the line
     * 
     */
    
    VEGETATION("vegetation"),
    
    PTI_19_19_ALIAS_3("pti19_19_Alias_3"),

    /**
     * Train struck animal   alias to TPEG Pti_19_19  object on the line
     * 
     */
    
    TRAIN_STRUCK_ANIMAL("trainStruckAnimal"),
    
    PTI_19_19_ALIAS_4("pti19_19_Alias_4"),

    /**
     * Train struck object   alias to TPEG Pti_19_19  object on the line
     * 
     */
    
    TRAIN_STRUCK_OBJECT("trainStruckObject"),
    
    PTI_19_20("pti19_20"),

    /**
     * TPEG Pti_19_20  animal on the line
     * 
     */
    
    ANIMAL_ON_THE_LINE("animalOnTheLine"),
    
    PTI_19_21("pti19_21"),

    /**
     * TPEG Pti_19_21  route diversion
     * 
     */
    
    ROUTE_DIVERSION("routeDiversion"),
    
    PTI_19_22("pti19_22"),

    /**
     * TPEG Pti_19_22  road closed
     * 
     */
    
    ROAD_CLOSED("roadClosed"),
    
    PTI_19_23("pti19_23"),

    /**
     * TPEG Pti_19_23  roadworks
     * 
     */
    
    ROADWORKS("roadworks"),
    
    PTI_19_24("pti19_24"),

    /**
     * TPEG Pti_19_24  special event
     * 
     */
    
    SPECIAL_EVENT("specialEvent"),
    
    PTI_19_24_ALIAS_1("pti19_24_Alias_1"),
    
    MARCH("march"),
    
    PTI_19_24_ALIAS_2("pti19_24_Alias_2"),
    
    PROCESSION("procession"),
    
    PTI_19_24_ALIAS_3("pti19_24_Alias_3"),
    
    DEMONSTRATION("demonstration"),
    
    PTI_19_24_ALIAS_4("pti19_24_Alias_4"),
    
    PUBLIC_DISTURBANCE("publicDisturbance"),
    
    PTI_19_24_ALIAS_5("pti19_24_Alias_5"),
    
    FILTER_BLOCKADE("filterBlockade"),
    
    PTI_19_24_ALIAS_6("pti19_24_Alias_6"),
    
    SIGHTSEERS_OBSTRUCTING_ACCESS("sightseersObstructingAccess"),
    
    PTI_19_25("pti19_25"),

    /**
     * TPEG Pti_19_25  bridge strike
     * 
     */
    
    BRIDGE_STRIKE("bridgeStrike"),
    
    PTI_19_26("pti19_26"),

    /**
     * TPEG Pti_19_26  overhead obstruction
     * 
     */
    
    OVERHEAD_OBSTRUCTION("overheadObstruction"),
    
    PTI_19_27("pti19_27"),

    /**
     * TPEG Pti_19_255 undefined problem
     * 
     */
    
    UNDEFINED_PROBLEM("undefinedProblem"),
    
    PTI_19_255_ALIAS_1(" pti19_255_Alias_1"),
    
    PROBLEMS_AT_BORDER_POST("problemsAtBorderPost"),
    
    PTI_19_255_ALIAS_2(" pti19_255_Alias_2"),
    
    PROBLEMS_AT_CUSTOMS_POST("problemsAtCustomsPost"),
    
    PTI_19_255_ALIAS_3(" pti19_255_Alias_3"),
    
    PROBLEMS_ON_LOCAL_ROAD("problemsOnLocalRoad");
    private final String value;

    MiscellaneousReasonEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MiscellaneousReasonEnumeration fromValue(String v) {
        for (MiscellaneousReasonEnumeration c: MiscellaneousReasonEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
