//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum MobilityFacilityEnumeration {

    
    PTI_23_255_4("pti23_255_4"),
    
    UNKNOWN("unknown"),
    
    PTI_23_16("pti23_16"),
    
    SUITABLE_FOR_WHEEL_CHAIRS("suitableForWheelChairs"),
    
    PTI_23_16_1("pti23_16_1"),
    
    LOW_FLOOR("lowFloor"),
    
    PTI_23_16_2("pti23_16_2"),
    
    BOARDING_ASSISTANCE("boardingAssistance"),
    
    PTI_23_16_3("pti23_16_3"),
    
    STEP_FREE_ACCESS("stepFreeAccess"),
    
    TACTILE_PATFORM_EDGES("tactilePatformEdges"),
    
    ONBOARD_ASSISTANCE("onboardAssistance"),
    
    UNACCOMPANIED_MINOR_ASSISTANCE("unaccompaniedMinorAssistance"),
    
    AUDIO_INFORMATION("audioInformation"),
    
    VISUAL_INFORMATION("visualInformation"),
    
    DISPLAYS_FOR_VISUALLY_IMPAIRED("displaysForVisuallyImpaired"),
    
    AUDIO_FOR_HEARING_IMPAIRED("audioForHearingImpaired");
    private final String value;

    MobilityFacilityEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MobilityFacilityEnumeration fromValue(String v) {
        for (MobilityFacilityEnumeration c: MobilityFacilityEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
