//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

public class NotifyByPagerAction extends PushedAction {

	
	protected String pagerGroupRef;
	protected String pager;

	/**
	 * Gets the value of the pagerGroupRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPagerGroupRef() {
		return pagerGroupRef;
	}

	/**
	 * Sets the value of the pagerGroupRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPagerGroupRef(String value) {
		this.pagerGroupRef = value;
	}

	/**
	 * Gets the value of the pager property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPager() {
		return pager;
	}

	/**
	 * Sets the value of the pager property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPager(String value) {
		this.pager = value;
	}

}
