//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum ParkingFacilityEnumeration {

    
    UNKNOWN("unknown"),
    
    CAR_PARK("carPark"),
    
    PARK_AND_RIDE_PARK("parkAndRidePark"),
    
    MOTORCYCLE_PARK("motorcyclePark"),
    
    CYCLE_PARK("cyclePark"),
    
    RENTAL_CAR_PARK("rentalCarPark"),
    
    COACH_PARK("coachPark");
    private final String value;

    ParkingFacilityEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParkingFacilityEnumeration fromValue(String v) {
        for (ParkingFacilityEnumeration c: ParkingFacilityEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
