//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum PassengerInformationFacilityEnumeration {

    
    UNKNOWN("unknown"),
    
    NEXT_STOP_INDICATOR("nextStopIndicator"),
    
    STOP_ANNOUNCEMENTS("stopAnnouncements"),
    
    PASSENGER_INFORMATION_DISPLAY("passengerInformationDisplay"),
    
    AUDIO_INFORMATION("audioInformation"),
    
    VISUAL_INFORMATION("visualInformation"),
    
    TACTILE_PLATFORM_EDGES("tactilePlatformEdges"),
    
    TACTILE_INFORMATION("tactileInformation"),
    
    WALKING_GUIDANCE("walkingGuidance"),
    
    JOURNEY_PLANNING("journeyPlanning"),
    
    LOST_FOUND("lostFound"),
    
    INFORMATION_DESK("informationDesk"),
    
    INTERACTIVE_KIOSK_DISPLAY("interactiveKiosk-Display"),
    
    PRINTED_PUBLIC_NOTICE("printedPublicNotice");
    private final String value;

    PassengerInformationFacilityEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PassengerInformationFacilityEnumeration fromValue(String v) {
        for (PassengerInformationFacilityEnumeration c: PassengerInformationFacilityEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
