//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum PassengerCommsFacilityEnumeration {

    
    UNKNOWN("unknown"),
    
    FACCOMMS_1("faccomms_1"),
    
    PASSENGER_WIFI("passengerWifi"),
    
    PTI_23_21("pti23_21"),
    
    TELEPHONE("telephone"),
    
    PTI_23_14("pti23_14"),
    
    AUDIO_SERVICES("audioServices"),
    
    PTI_23_15("pti23_15"),
    
    VIDEO_SERVICES("videoServices"),
    
    PTI_23_25("pti23_25"),
    
    BUSINESS_SERVICES("businessServices"),
    
    INTERNET("internet"),
    
    POSTOFFICE("postoffice"),
    
    LETTERBOX("letterbox");
    private final String value;

    PassengerCommsFacilityEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PassengerCommsFacilityEnumeration fromValue(String v) {
        for (PassengerCommsFacilityEnumeration c: PassengerCommsFacilityEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
