//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

import java.util.ArrayList;
import java.util.List;
import uk.org.ifopt.acsb.Suitability;

public class PtConsequence {


    protected HalfOpenTimestampRange period;

    protected ServiceConditionEnumeration condition;

    protected SeverityEnumeration severity;

    protected AffectsScope affects;

    protected PtConsequence.Suitabilities suitabilities;

    protected PtAdvice advice;

    protected Blocking blocking;

    protected Boarding boarding;

    protected Delays delays;

    protected Casualties casualties;

    protected List<Easements> easements;

    protected Extensions extensions;

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link HalfOpenTimestampRange }
     *     
     */
    public HalfOpenTimestampRange getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link HalfOpenTimestampRange }
     *     
     */
    public void setPeriod(HalfOpenTimestampRange value) {
        this.period = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceConditionEnumeration }
     *     
     */
    public ServiceConditionEnumeration getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceConditionEnumeration }
     *     
     */
    public void setCondition(ServiceConditionEnumeration value) {
        this.condition = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link SeverityEnumeration }
     *     
     */
    public SeverityEnumeration getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeverityEnumeration }
     *     
     */
    public void setSeverity(SeverityEnumeration value) {
        this.severity = value;
    }

    /**
     * Gets the value of the affects property.
     * 
     * @return
     *     possible object is
     *     {@link AffectsScope }
     *     
     */
    public AffectsScope getAffects() {
        return affects;
    }

    /**
     * Sets the value of the affects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AffectsScope }
     *     
     */
    public void setAffects(AffectsScope value) {
        this.affects = value;
    }

    /**
     * Gets the value of the suitabilities property.
     * 
     * @return
     *     possible object is
     *     {@link PtConsequence.Suitabilities }
     *     
     */
    public PtConsequence.Suitabilities getSuitabilities() {
        return suitabilities;
    }

    /**
     * Sets the value of the suitabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtConsequence.Suitabilities }
     *     
     */
    public void setSuitabilities(PtConsequence.Suitabilities value) {
        this.suitabilities = value;
    }

    /**
     * Gets the value of the advice property.
     * 
     * @return
     *     possible object is
     *     {@link PtAdvice }
     *     
     */
    public PtAdvice getAdvice() {
        return advice;
    }

    /**
     * Sets the value of the advice property.
     * 
     * @param value
     *     allowed object is
     *     {@link PtAdvice }
     *     
     */
    public void setAdvice(PtAdvice value) {
        this.advice = value;
    }

    /**
     * Gets the value of the blocking property.
     * 
     * @return
     *     possible object is
     *     {@link Blocking }
     *     
     */
    public Blocking getBlocking() {
        return blocking;
    }

    /**
     * Sets the value of the blocking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Blocking }
     *     
     */
    public void setBlocking(Blocking value) {
        this.blocking = value;
    }

    /**
     * Gets the value of the boarding property.
     * 
     * @return
     *     possible object is
     *     {@link Boarding }
     *     
     */
    public Boarding getBoarding() {
        return boarding;
    }

    /**
     * Sets the value of the boarding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boarding }
     *     
     */
    public void setBoarding(Boarding value) {
        this.boarding = value;
    }

    /**
     * Gets the value of the delays property.
     * 
     * @return
     *     possible object is
     *     {@link Delays }
     *     
     */
    public Delays getDelays() {
        return delays;
    }

    /**
     * Sets the value of the delays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Delays }
     *     
     */
    public void setDelays(Delays value) {
        this.delays = value;
    }

    /**
     * Gets the value of the casualties property.
     * 
     * @return
     *     possible object is
     *     {@link Casualties }
     *     
     */
    public Casualties getCasualties() {
        return casualties;
    }

    /**
     * Sets the value of the casualties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Casualties }
     *     
     */
    public void setCasualties(Casualties value) {
        this.casualties = value;
    }

    /**
     * Gets the value of the easements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the easements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEasements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Easements }
     * 
     * 
     */
    public List<Easements> getEasements() {
        if (easements == null) {
            easements = new ArrayList<Easements>();
        }
        return this.easements;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }


   
    public static class Suitabilities {

   
        protected List<Suitability> suitability;

        /**
         * Gets the value of the suitability property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the suitability property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSuitability().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Suitability }
         * 
         * 
         */
        public List<Suitability> getSuitability() {
            if (suitability == null) {
                suitability = new ArrayList<Suitability>();
            }
            return this.suitability;
        }

    }

}
