//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

public class PublishToWebAction extends ParameterisedAction {

	protected Boolean incidents;

	protected Boolean homePage;

	protected Boolean ticker;

	/**
	 * Gets the value of the incidents property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isIncidents() {
		return incidents;
	}

	/**
	 * Sets the value of the incidents property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setIncidents(Boolean value) {
		this.incidents = value;
	}

	/**
	 * Gets the value of the homePage property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isHomePage() {
		return homePage;
	}

	/**
	 * Sets the value of the homePage property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setHomePage(Boolean value) {
		this.homePage = value;
	}

	/**
	 * Gets the value of the ticker property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isTicker() {
		return ticker;
	}

	/**
	 * Sets the value of the ticker property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setTicker(Boolean value) {
		this.ticker = value;
	}

}
