//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

public class PublishToTvAction extends ParameterisedAction {

	
	protected Boolean ceefax;
	
	protected Boolean teletext;

	/**
	 * Gets the value of the ceefax property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isCeefax() {
		return ceefax;
	}

	/**
	 * Sets the value of the ceefax property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setCeefax(Boolean value) {
		this.ceefax = value;
	}

	/**
	 * Gets the value of the teletext property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isTeletext() {
		return teletext;
	}

	/**
	 * Sets the value of the teletext property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setTeletext(Boolean value) {
		this.teletext = value;
	}

}
