//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

public class PublishToAlertsAction extends PushedAction {

	
	protected Boolean byEmail;
	
	protected Boolean byMobile;

	/**
	 * Gets the value of the byEmail property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isByEmail() {
		return byEmail;
	}

	/**
	 * Sets the value of the byEmail property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setByEmail(Boolean value) {
		this.byEmail = value;
	}

	/**
	 * Gets the value of the byMobile property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isByMobile() {
		return byMobile;
	}

	/**
	 * Sets the value of the byMobile property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setByMobile(Boolean value) {
		this.byMobile = value;
	}

}
