//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

import java.util.ArrayList;
import java.util.List;

import javax.xml.datatype.Duration;

public class PushedAction extends ParameterisedAction {

	
	protected PushedAction.BeforeNotices beforeNotices;
	
	protected Boolean clearNotice;

	/**
	 * Gets the value of the beforeNotices property.
	 * 
	 * @return possible object is {@link PushedAction.BeforeNotices }
	 * 
	 */
	public PushedAction.BeforeNotices getBeforeNotices() {
		return beforeNotices;
	}

	/**
	 * Sets the value of the beforeNotices property.
	 * 
	 * @param value
	 *            allowed object is {@link PushedAction.BeforeNotices }
	 * 
	 */
	public void setBeforeNotices(PushedAction.BeforeNotices value) {
		this.beforeNotices = value;
	}

	/**
	 * Gets the value of the clearNotice property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isClearNotice() {
		return clearNotice;
	}

	/**
	 * Sets the value of the clearNotice property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setClearNotice(Boolean value) {
		this.clearNotice = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Interval" type="{http://www.siri.org.uk/siri}DurationType" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	
	public static class BeforeNotices {

		
		protected List<Duration> interval;

		/**
		 * Gets the value of the interval property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the interval property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getInterval().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Duration }
		 * 
		 * 
		 */
		public List<Duration> getInterval() {
			if (interval == null) {
				interval = new ArrayList<Duration>();
			}
			return this.interval;
		}

	}

}
