//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum SanitaryFacilityEnumeration {

    
    UNKNOWN("unknown"),
    
    PTI_23_22("pti23_22"),
    
    TOILET("toilet"),
    
    PTI_23_23("pti23_23"),
    
    NO_TOILET("noToilet"),
    
    SHOWER("shower"),
    
    WHEELCHAIR_ACCCESS_TOILET("wheelchairAcccessToilet"),
    
    BABY_CHANGE("babyChange");
    private final String value;

    SanitaryFacilityEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SanitaryFacilityEnumeration fromValue(String v) {
        for (SanitaryFacilityEnumeration c: SanitaryFacilityEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
