//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum ScopeTypeEnumeration {

    
    GENERAL("general"),
    
    OPERATOR("operator"),
    
    NETWORK("network"),
    
    ROUTE("route"),
    
    LINE("line"),
    
    PLACE("place"),
    
    STOP_PLACE("stopPlace"),
    
    STOP_PLACE_COMPONENT("stopPlaceComponent"),
    
    STOP_POINT("stopPoint"),
    
    VEHICLE_JOURNEY("vehicleJourney"),
    
    DATED_VEHICLE_JOURNEY("datedVehicleJourney"),
    
    CONNECTION_LINK("connectionLink"),
    
    INTERCHANGE("interchange"),
    
    ROAD("road");
    private final String value;

    ScopeTypeEnumeration(String v) {
        value = v;
    }

    public static ScopeTypeEnumeration fromString(String v) {
		if (v != null) {
			for (ScopeTypeEnumeration c : ScopeTypeEnumeration.values()) {
				if (v.equalsIgnoreCase(c.toString())) {
			          return c;
			    }				
			}
		}
		throw new IllegalArgumentException(v);
	}

	@Override
	public String toString() {
		return value;
	}

}
