//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public class SituationRef {


    protected String situationSimpleRef;
    protected String situationFullRef;

    /**
     * Gets the value of the situationSimpleRef property.
     * 
     * @return
     *     possible object is
     *     {@link SituationSimpleRef }
     *     
     */
    
    public String getSituationSimpleRef() {
        return situationSimpleRef;
    }

    /**
     * Sets the value of the situationSimpleRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SituationSimpleRef }
     *     
     */
    
    public void setSituationSimpleRef(String value) {
        this.situationSimpleRef = value;
    }

    /**
     * Reference to a  Situation. Elements of Situation identfier are expressed as atomic elements
     * 
     * @return
     *     possible object is
     *     {@link SituationFullRef }
     *     
     */
    
    public String getSituationFullRef() {
        return situationFullRef;
    }

    /**
     * Sets the value of the situationFullRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SituationFullRef }
     *     
     */
    
    public void setSituationFullRef(String value) {
        this.situationFullRef = value;
    }

}
