//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum SituationSourceTypeEnumeration {

  
    DIRECT_REPORT("directReport"),
  
    EMAIL("email"),
  
    PHONE("phone"),
  
    FAX("fax"),
  
    POST("post"),
  
    FEED("feed"),
  
    RADIO("radio"),
  
    TV("tv"),
  
    WEB("web"),
  
    PAGER("pager"),
  
    TEXT("text"),
  
    OTHER("other");
    private final String value;

    SituationSourceTypeEnumeration(String v) {
        value = v;
    }

    public static SituationSourceTypeEnumeration fromString(String v) {
		if (v != null) {
			for (SituationSourceTypeEnumeration c : SituationSourceTypeEnumeration.values()) {
				if (v.equalsIgnoreCase(c.toString())) {
			          return c;
			    }				
			}
		}
		throw new IllegalArgumentException(v);
	}

	@Override
	public String toString() {
		return value;
	}

}
