//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

import java.util.Date;

public class SituationElement extends AbstractSituationElement {

	protected References references;

	protected SituationSource source;
	protected Date versionedAtTime;

	/**
	 * Gets the value of the references property.
	 * 
	 * @return possible object is {@link References }
	 * 
	 */
	public References getReferences() {
		return references;
	}

	/**
	 * Sets the value of the references property.
	 * 
	 * @param value
	 *            allowed object is {@link References }
	 * 
	 */
	public void setReferences(References value) {
		this.references = value;
	}

	/**
	 * Gets the value of the source property.
	 * 
	 * @return possible object is {@link SituationSource }
	 * 
	 */
	public SituationSource getSource() {
		return source;
	}

	/**
	 * Sets the value of the source property.
	 * 
	 * @param value
	 *            allowed object is {@link SituationSource }
	 * 
	 */
	public void setSource(SituationSource value) {
		this.source = value;
	}

	/**
	 * Gets the value of the versionedAtTime property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getVersionedAtTime() {
		return versionedAtTime;
	}

	/**
	 * Sets the value of the versionedAtTime property.
	 * 
	 * @param value
	 *            allowed object is {@link Date }
	 * 
	 */
	public void setVersionedAtTime(Date value) {
		this.versionedAtTime = value;
	}

}
