//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum StopPointTypeEnumeration {

    
    PTI_17_0("pti17_0"),
    
    UNKNOWN("unknown"),
    
    PTI_17_1("pti17_1"),
    
    PLATFORM_NUMBER("platformNumber"),
    
    PTI_17_2("pti17_2"),
    
    TERMINAL_GATE("terminalGate"),
    
    PTI_17_3("pti17_3"),
    
    FERRY_BERTH("ferryBerth"),
    
    PTI_17_4("pti17_4"),
    
    HARBOUR_PIER("harbourPier"),
    
    PTI_17_5("pti17_5"),
    
    LANDING_STAGE("landingStage"),
    
    PTI_17_6("pti17_6"),
    
    BUS_STOP("busStop"),
    
    PTI_17_255("pti17_255"),
    
    UNDEFINED_BOOKING_INFORMATION("undefinedBookingInformation");
    private final String value;

    StopPointTypeEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StopPointTypeEnumeration fromValue(String v) {
        for (StopPointTypeEnumeration c: StopPointTypeEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
