//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum TicketingFacilityEnumeration {

    
    UNKNOWN("unknown"),
    
    TICKET_MACHINES("ticketMachines"),
    
    TICKET_OFFICE("ticketOffice"),
    
    TICKET_ON_DEMAND_MACHINES("ticketOnDemandMachines"),
    
    TICKET_SALES("ticketSales"),
    
    MOBILE_TICKETING("mobileTicketing"),
    
    TICKET_COLLECTION("ticketCollection"),
    
    CENTRAL_RESERVATIONS("centralReservations"),
    
    LOCAL_TICKETS("localTickets"),
    
    NATIONAL_TICKETS("nationalTickets"),
    
    INTERNATIONAL_TICKETS("internationalTickets");
    private final String value;

    TicketingFacilityEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TicketingFacilityEnumeration fromValue(String v) {
        for (TicketingFacilityEnumeration c: TicketingFacilityEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
