//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum TicketRestrictionEnumeration {

    
    PTI_25_0("pti25_0"),
    
    UNKNOWN("unknown"),
    
    PTI_25_1("pti25_1"),
    
    ALL_TICKET_CLASSES_VALID("allTicketClassesValid"),
    
    PTI_25_2("pti25_2"),
    
    FULL_FARE_ONLY("fullFareOnly"),
    
    PTI_25_3("pti25_3"),
    
    CERTAIN_TICKETS_ONLY("certainTicketsOnly"),
    
    PTI_25_4("pti25_4"),
    
    TICKET_WITH_RESERVATION("ticketWithReservation"),
    
    PTI_25_5("pti25_5"),
    
    SPECIAL_FARE("specialFare"),
    
    PTI_25_6("pti25_6"),
    
    ONLY_TICKETS_OF_SPECIFIED_OPERATOR("onlyTicketsOfSpecifiedOperator"),
    
    PTI_25_7("pti25_7"),
    
    NO_RESTRICTIONS("noRestrictions"),
    
    PTI_25_8("pti25_8"),
    
    NO_OFF_PEAK_TICKETS("noOffPeakTickets"),
    
    PTI_25_9("pti25_9"),
    
    NO_WEEKEND_RETURN_TICKETS("noWeekendReturnTickets"),
    
    PTI_25_10("pti25_10"),
    
    NO_REDUCED_FARE_TICKETS("noReducedFareTickets"),
    
    PTI_25_255("pti25_255"),
    
    UNKNOWN_TICKET_RESTRICTION("unknownTicketRestriction");
    private final String value;

    TicketRestrictionEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TicketRestrictionEnumeration fromValue(String v) {
        for (TicketRestrictionEnumeration c: TicketRestrictionEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
