//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//

package uk.org.siri.siri;

import java.util.Date;

public class VehicleActivity {

	protected Date recordedAtTime;

	protected MonitoredVehicleJourney monitoredVehicleJourney;

	/**
	 * Gets the value of the monitoredVehicleJourney property.
	 * 
	 * @return possible object is
	 *         {@link VehicleActivity.MonitoredVehicleJourney }
	 * 
	 */
	
	public MonitoredVehicleJourney getMonitoredVehicleJourney() {
		return monitoredVehicleJourney;
	}

	/**
	 * Sets the value of the monitoredVehicleJourney property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link VehicleActivity.MonitoredVehicleJourney }
	 * 
	 */
	
	public void setMonitoredVehicleJourney(MonitoredVehicleJourney value) {
		this.monitoredVehicleJourney = value;
	}
	
	public Date getRecordedAtTime() {
		return recordedAtTime;
	}
	
	public void setRecordedAtTime(Date recordedAtTime) {
		this.recordedAtTime = recordedAtTime;
	}

}
