//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum VehicleModesOfTransportEnumeration {

    
    PTI_1_0("pti1_0"),
    
    UNKNOWN("unknown"),
    
    PTI_1_1("pti1_1"),

    /**
     * See pti2_x
     * 
     */
    
    RAILWAY_SERVICE("railwayService"),
    
    RAIL("rail"),
    
    PTI_1_2("pti1_2"),

    /**
     * See pti3_x
     * 
     */
    
    COACH_SERVICE("coachService"),
    
    COACH("coach"),
    
    PTI_1_3("pti1_3"),
    
    SUBURBAN_RAILWAY_SERVICE("suburbanRailwayService"),
    
    SUBURBAN_RAIL("suburbanRail"),
    
    PTI_1_4("pti1_4"),

    /**
     * See pti4_x
     * 
     */
    
    URBAN_RAILWAY_SERVICE("urbanRailwayService"),
    
    URBAN_RAIL("urbanRail"),
    
    PTI_1_5("pti1_5"),
    
    METRO_SERVICE("metroService"),
    
    METRO("metro"),
    
    PTI_1_6("pti1_6"),
    
    UNDERGROUND_SERVICE("undergroundService"),
    
    UNDERGROUND("underground"),
    
    PTI_1_7("pti1_7"),

    /**
     * See pti5_x
     * 
     */
    
    BUS_SERVICE("busService"),
    
    BUS("bus"),
    
    PTI_1_8("pti1_8"),
    
    TROLLEY_BUS_SERVICE("trolleyBusService"),
    
    TROLLEY_BUS("trolleyBus"),
    
    PTI_1_9("pti1_9"),

    /**
     * See pti6_x
     * 
     */
    
    TRAM_SERVICE("tramService"),
    
    TRAM("tram"),
    
    PTI_1_10("pti1_10"),

    /**
     * See pti7_x
     * 
     */
    
    WATER_TRANSPORT_SERVICE("waterTransportService"),
    
    WATER_TRANSPORT("waterTransport"),
    
    PTI_1_11("pti1_11"),

    /**
     * See pti8_x
     * 
     */
    
    AIR_SERVICE("airService"),
    
    AIR("air"),
    
    PTI_1_12("pti1_12"),
    
    FERRY_SERVICE("ferryService"),
    
    WATER("water"),
    
    PTI_1_13("pti1_13"),

    /**
     * See pti9_x
     * 
     */
    
    TELECABIN_SERVICE("telecabinService"),
    
    TELECABIN("telecabin"),
    
    PTI_1_14("pti1_14"),

    /**
     * See pti10_x
     * 
     */
    
    FUNICULAR_SERVICE("funicularService"),
    
    FUNICULAR("funicular"),
    
    PTI_1_15("pti1_15"),

    /**
     * pti11_x
     * 
     */
    
    TAXI_SERVICE("taxiService"),
    
    TAXI("taxi"),
    
    PTI_1_16("pti1_16"),

    /**
     * See pti12_x
     * 
     */
    
    SELF_DRIVE("selfDrive"),
    
    PTI_1_17("pti1_17"),
    
    ALL_SERVICES("allServices"),
    
    ALL("all"),
    
    PTI_1_18("pti1_18"),
    
    ALL_SERVICES_EXCEPT("allServicesExcept");
    private final String value;

    VehicleModesOfTransportEnumeration(String v) {
        value = v;
    }

    public static VehicleModesOfTransportEnumeration fromString(String v) {
		if (v != null) {
			for (VehicleModesOfTransportEnumeration c : VehicleModesOfTransportEnumeration.values()) {
				if (v.equalsIgnoreCase(c.toString())) {
			          return c;
			    }				
			}
		}
		throw new IllegalArgumentException(v);
	}

	@Override
	public String toString() {
		return value;
	}

}
