//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.siri.siri;

public enum VerificationStatusEnumeration {

    
    PTI_32_0("pti32_0"),
    
    UNKNOWN("unknown"),
    
    PTI_32_1("pti32_1"),
    
    UNVERIFIED("unverified"),
    
    PTI_32_255("pti32_255"),
    
    VERIFIED("verified"),
    
    VERIFIED_AS_DUPLICATE("verifiedAsDuplicate");
    private final String value;

    VerificationStatusEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VerificationStatusEnumeration fromString(String v) {
		if (v != null) {
			for (VerificationStatusEnumeration c : VerificationStatusEnumeration.values()) {
				if (v.equalsIgnoreCase(c.toString())) {
			          return c;
			    }				
			}
		}
		throw new IllegalArgumentException(v);
	}

	@Override
	public String toString() {
		return value;
	}

}
