//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.ifopt.acsb;

import java.util.ArrayList;
import java.util.List;
import uk.org.ifopt.ifopt.Extensions;

public class AccessibilityAssessment {


    protected boolean mobilityImpairedAccess;

    protected AccessibilityAssessment.Limitations limitations;

    protected AccessibilityAssessment.Suitabilities suitabilities;

    protected Extensions extensions;

    /**
     * Gets the value of the mobilityImpairedAccess property.
     * 
     */
    public boolean isMobilityImpairedAccess() {
        return mobilityImpairedAccess;
    }

    /**
     * Sets the value of the mobilityImpairedAccess property.
     * 
     */
    public void setMobilityImpairedAccess(boolean value) {
        this.mobilityImpairedAccess = value;
    }

    /**
     * Gets the value of the limitations property.
     * 
     * @return
     *     possible object is
     *     {@link AccessibilityAssessment.Limitations }
     *     
     */
    public AccessibilityAssessment.Limitations getLimitations() {
        return limitations;
    }

    /**
     * Sets the value of the limitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessibilityAssessment.Limitations }
     *     
     */
    public void setLimitations(AccessibilityAssessment.Limitations value) {
        this.limitations = value;
    }

    /**
     * Gets the value of the suitabilities property.
     * 
     * @return
     *     possible object is
     *     {@link AccessibilityAssessment.Suitabilities }
     *     
     */
    public AccessibilityAssessment.Suitabilities getSuitabilities() {
        return suitabilities;
    }

    /**
     * Sets the value of the suitabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessibilityAssessment.Suitabilities }
     *     
     */
    public void setSuitabilities(AccessibilityAssessment.Suitabilities value) {
        this.suitabilities = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

    public static class Limitations {

        protected List<AccessibilityLimitation> accessibilityLimitation;

        /**
         * Gets the value of the accessibilityLimitation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the accessibilityLimitation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccessibilityLimitation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AccessibilityLimitation }
         * 
         * 
         */
        public List<AccessibilityLimitation> getAccessibilityLimitation() {
            if (accessibilityLimitation == null) {
                accessibilityLimitation = new ArrayList<AccessibilityLimitation>();
            }
            return this.accessibilityLimitation;
        }

    }

    public static class Suitabilities {

    
        protected List<Suitability> suitability;

        /**
         * Gets the value of the suitability property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the suitability property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSuitability().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Suitability }
         * 
         * 
         */
        public List<Suitability> getSuitability() {
            if (suitability == null) {
                suitability = new ArrayList<Suitability>();
            }
            return this.suitability;
        }

    }

}
