//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.ifopt.acsb;

public enum MobilityEnumeration {

    
    WHEELCHAIR("wheelchair"),
    
    ASSISTED_WHEELCHAIR("assistedWheelchair"),
    
    MOTORIZED_WHEELCHAIR("motorizedWheelchair"),
    
    WALKING_FRAME("walkingFrame"),
    
    RESTRICTED_MOBILITY("restrictedMobility"),
    
    OTHER_MOBILITY_NEED("otherMobilityNeed");
    private final String value;

    MobilityEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MobilityEnumeration fromValue(String v) {
        for (MobilityEnumeration c: MobilityEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
