//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.ifopt.acsb;

public class Suitability {


    protected SuitabilityEnumeration suitable;

    protected UserNeed userNeed;

    /**
     * Gets the value of the suitable property.
     * 
     * @return
     *     possible object is
     *     {@link SuitabilityEnumeration }
     *     
     */
    public SuitabilityEnumeration getSuitable() {
        return suitable;
    }

    /**
     * Sets the value of the suitable property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuitabilityEnumeration }
     *     
     */
    public void setSuitable(SuitabilityEnumeration value) {
        this.suitable = value;
    }

    /**
     * Gets the value of the userNeed property.
     * 
     * @return
     *     possible object is
     *     {@link UserNeed }
     *     
     */
    public UserNeed getUserNeed() {
        return userNeed;
    }

    /**
     * Sets the value of the userNeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserNeed }
     *     
     */
    public void setUserNeed(UserNeed value) {
        this.userNeed = value;
    }

}
