//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.ifopt.ifopt;

import java.util.ArrayList;
import java.util.List;
public class AbstractProjection {

    
    protected AbstractProjection.Features features;

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractProjection.Features }
     *     
     */
    public AbstractProjection.Features getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractProjection.Features }
     *     
     */
    public void setFeatures(AbstractProjection.Features value) {
        this.features = value;
    }


  
    public static class Features {

  
        protected List<FeatureRef> gisFeatureRef;

        /**
         * Gets the value of the gisFeatureRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the gisFeatureRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGisFeatureRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureRef }
         * 
         * 
         */
        public List<FeatureRef> getGisFeatureRef() {
            if (gisFeatureRef == null) {
                gisFeatureRef = new ArrayList<FeatureRef>();
            }
            return this.gisFeatureRef;
        }

    }

}
