//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.ifopt.ifopt;

public enum AccessibilityFeatureEnumeration {

    
    LIFT("lift"),
    
    STAIRS("stairs"),
    
    SERIES_OF_STAIRS("seriesOfStairs"),
    
    ESCALATOR("escalator"),
    
    TRAVELATOR("travelator"),
    
    RAMP("ramp"),
    
    SHUTTLE("shuttle"),
    
    BARRIER("barrier"),
    
    NARROW_ENTRANCE("narrowEntrance"),
    
    CONFINED_SPACE("confinedSpace"),
    
    QUEUE_MANAGEMENT("queueManagement"),
    
    NONE("none"),
    
    UNKNOWN("unknown"),
    
    OTHER("other");
    private final String value;

    AccessibilityFeatureEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AccessibilityFeatureEnumeration fromValue(String v) {
        for (AccessibilityFeatureEnumeration c: AccessibilityFeatureEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
