//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.ifopt.ifopt;

public class FeatureRef {

    
    protected FeatureIdRef featureIdRef;
    protected String featureType;

    /**
     * Gets the value of the featureIdRef property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureIdRef }
     *     
     */
    public FeatureIdRef getFeatureIdRef() {
        return featureIdRef;
    }

    /**
     * Sets the value of the featureIdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureIdRef }
     *     
     */
    public void setFeatureIdRef(FeatureIdRef value) {
        this.featureIdRef = value;
    }

    /**
     * Gets the value of the featureType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureType() {
        return featureType;
    }

    /**
     * Sets the value of the featureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureType(String value) {
        this.featureType = value;
    }

}
