//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.ifopt.ifopt;


public enum IanaCountryTldEnumeration {


    /**
     * Ascension Island
     * 
     */

    AC("ac"),

    /**
     * Andorra
     * 
     */

    AD("ad"),

    /**
     * United Arab Emirates
     * 
     */

    AE("ae"),

    /**
     * Afghanistan
     * 
     */
    
    AF("af"),

    /**
     * Antigua and Barbuda
     * 
     */
    
    AG("ag"),

    /**
     * Anguilla
     * 
     */
    
    AI("ai"),

    /**
     * Albania
     * 
     */
    
    AL("al"),

    /**
     * Armenia
     * 
     */
    
    AM("am"),

    /**
     * Netherlands Antilles
     * 
     */
    
    AN("an"),

    /**
     * Angola
     * 
     */
    
    AO("ao"),

    /**
     * Antarctica
     * 
     */
    
    AQ("aq"),

    /**
     * Argentina
     * 
     */
    
    AR("ar"),

    /**
     * American Samoa
     * 
     */
    
    AS("as"),

    /**
     * Austria
     * 
     */
    
    AT("at"),

    /**
     * Australia
     * 
     */
    
    AU("au"),

    /**
     * Aruba
     * 
     */
    
    AW("aw"),

    /**
     * Azerbaijan
     * 
     */
    
    AZ("az"),

    /**
     * Aland Islands
     * 
     */
    
    AX("ax"),

    /**
     * Bosnia and Herzegovina
     * 
     */
    
    BA("ba"),

    /**
     * Barbados
     * 
     */
    
    BB("bb"),

    /**
     * Bangladesh
     * 
     */
    
    BD("bd"),

    /**
     * Belgium
     * 
     */
    
    BE("be"),

    /**
     * Burkina Faso
     * 
     */
    
    BF("bf"),

    /**
     * Bulgaria
     * 
     */
    
    BG("bg"),

    /**
     * Bahrain
     * 
     */
    
    BH("bh"),

    /**
     * Burundi
     * 
     */
    
    BI("bi"),

    /**
     * Benin
     * 
     */
    
    BJ("bj"),

    /**
     * Bermuda
     * 
     */
    
    BM("bm"),

    /**
     * Brunei Darussalam
     * 
     */
    
    BN("bn"),

    /**
     * Bolivia
     * 
     */
    
    BO("bo"),

    /**
     * Brazil
     * 
     */
    
    BR("br"),

    /**
     * Bahamas
     * 
     */
    
    BS("bs"),

    /**
     * Bhutan
     * 
     */
    
    BT("bt"),

    /**
     * Bouvet Island
     * 
     */
    
    BV("bv"),

    /**
     * Botswana
     * 
     */
    
    BW("bw"),

    /**
     * Belarus
     * 
     */
    
    BY("by"),

    /**
     * Belize
     * 
     */
    
    BZ("bz"),

    /**
     * Canada
     * 
     */
    
    CA("ca"),

    /**
     * Cocos (Keeling) Islands
     * 
     */
    
    CC("cc"),

    /**
     * Congo, The Democratic Republic of the
     * 
     */
    
    CD("cd"),

    /**
     * Central African Republic
     * 
     */
    
    CF("cf"),

    /**
     * Congo, Republic of
     * 
     */
    
    CG("cg"),

    /**
     * Switzerland
     * 
     */
    
    CH("ch"),

    /**
     * Cote d'Ivoire
     * 
     */
    
    CI("ci"),

    /**
     * Cook Islands
     * 
     */
    
    CK("ck"),

    /**
     * Chile
     * 
     */
    
    CL("cl"),

    /**
     * Cameroon
     * 
     */
    
    CM("cm"),

    /**
     * China
     * 
     */
    
    CN("cn"),

    /**
     * Colombia
     * 
     */
    
    CO("co"),

    /**
     * Costa Rica
     * 
     */
    
    CR("cr"),

    /**
     * Serbia and Montenegro
     * 
     */
    
    CS("cs"),

    /**
     * Cuba
     * 
     */
    
    CU("cu"),

    /**
     * Cape Verde
     * 
     */
    
    CV("cv"),

    /**
     * Christmas Island
     * 
     */
    
    CX("cx"),

    /**
     * Cyprus
     * 
     */
    
    CY("cy"),

    /**
     * Czech Republic
     * 
     */
    
    CZ("cz"),

    /**
     * Germany
     * 
     */
    
    DE("de"),

    /**
     * Djibouti
     * 
     */
    
    DJ("dj"),

    /**
     * Denmark
     * 
     */
    
    DK("dk"),

    /**
     * Dominica
     * 
     */
    
    DM("dm"),

    /**
     * Dominican Republic
     * 
     */
    
    DO("do"),

    /**
     * Algeria
     * 
     */
    
    DZ("dz"),

    /**
     * Ecuador
     * 
     */
    
    EC("ec"),

    /**
     * Estonia
     * 
     */
    
    EE("ee"),

    /**
     * Egypt
     * 
     */
    
    EG("eg"),

    /**
     * Western Sahara
     * 
     */
    
    EH("eh"),

    /**
     * Eritrea
     * 
     */
    
    ER("er"),

    /**
     * Spain
     * 
     */
    
    ES("es"),

    /**
     * Ethiopia
     * 
     */
    
    ET("et"),

    /**
     * European Union
     * 
     */
    
    EU("eu"),

    /**
     * Finland
     * 
     */
    
    FI("fi"),

    /**
     * Fiji
     * 
     */
    
    FJ("fj"),

    /**
     * Falkland Islands (Malvinas)
     * 
     */
    
    FK("fk"),

    /**
     * Micronesia, Federal State of
     * 
     */
    
    FM("fm"),

    /**
     * Faroe Islands
     * 
     */
    
    FO("fo"),

    /**
     * France
     * 
     */
    
    FR("fr"),

    /**
     * Gabon
     * 
     */
    
    GA("ga"),

    /**
     * United Kingdom
     * 
     */
    
    GB("gb"),

    /**
     * Grenada
     * 
     */
    
    GD("gd"),

    /**
     * Georgia
     * 
     */
    
    GE("ge"),

    /**
     * French Guiana
     * 
     */
    
    GF("gf"),

    /**
     * Guernsey
     * 
     */
    
    GG("gg"),

    /**
     * Ghana
     * 
     */
    
    GH("gh"),

    /**
     * Gibraltar
     * 
     */
    
    GI("gi"),

    /**
     * Greenland
     * 
     */
    
    GL("gl"),

    /**
     * Gambia
     * 
     */
    
    GM("gm"),

    /**
     * Guinea
     * 
     */
    
    GN("gn"),

    /**
     * Guadeloupe
     * 
     */
    
    GP("gp"),

    /**
     * Equatorial Guinea
     * 
     */
    
    GQ("gq"),

    /**
     * Greece
     * 
     */
    
    GR("gr"),

    /**
     * South Georgia and the South Sandwich Islands
     * 
     */
    
    GS("gs"),

    /**
     * Guatemala
     * 
     */
    
    GT("gt"),

    /**
     * Guam
     * 
     */
    
    GU("gu"),

    /**
     * Guinea-Bissau
     * 
     */
    
    GW("gw"),

    /**
     * Guyana
     * 
     */
    
    GY("gy"),

    /**
     * Hong Kong
     * 
     */
    
    HK("hk"),

    /**
     * Heard and McDonald Islands
     * 
     */
    
    HM("hm"),

    /**
     * Honduras
     * 
     */
    
    HN("hn"),

    /**
     * Croatia/Hrvatska
     * 
     */
    
    HR("hr"),

    /**
     * Haiti
     * 
     */
    
    HT("ht"),

    /**
     * Hungary
     * 
     */
    
    HU("hu"),

    /**
     * Indonesia
     * 
     */
    
    ID("id"),

    /**
     * Ireland
     * 
     */
    
    IE("ie"),

    /**
     * Israel
     * 
     */
    
    IL("il"),

    /**
     * Isle of Man
     * 
     */
    
    IM("im"),

    /**
     * India
     * 
     */
    
    IN("in"),

    /**
     * British Indian Ocean Territory
     * 
     */
    
    IO("io"),

    /**
     * Iraq
     * 
     */
    
    IQ("iq"),

    /**
     * Iran, Islamic Republic of
     * 
     */
    
    IR("ir"),

    /**
     * Iceland
     * 
     */
    
    IS("is"),

    /**
     * Italy
     * 
     */
    
    IT("it"),

    /**
     * Jersey
     * 
     */
    
    JE("je"),

    /**
     * Jamaica
     * 
     */
    
    JM("jm"),

    /**
     * Jordan
     * 
     */
    
    JO("jo"),

    /**
     * Japan
     * 
     */
    
    JP("jp"),

    /**
     * Kenya
     * 
     */
    
    KE("ke"),

    /**
     * Kyrgyzstan
     * 
     */
    
    KG("kg"),

    /**
     * Cambodia
     * 
     */
    
    KH("kh"),

    /**
     * Kiribati
     * 
     */
    
    KI("ki"),

    /**
     * Comoros
     * 
     */
    
    KM("km"),

    /**
     * Saint Kitts and Nevis
     * 
     */
    
    KN("kn"),

    /**
     * Korea, Democratic People's Republic
     * 
     */
    
    KP("kp"),

    /**
     * Korea, Republic of
     * 
     */
    
    KR("kr"),

    /**
     * Kuwait
     * 
     */
    
    KW("kw"),

    /**
     * Cayman Islands
     * 
     */
    
    KY("ky"),

    /**
     * Kazakhstan
     * 
     */
    
    KZ("kz"),

    /**
     * Lao People's Democratic Republic
     * 
     */
    
    LA("la"),

    /**
     * Lebanon
     * 
     */
    
    LB("lb"),

    /**
     * Saint Lucia
     * 
     */
    
    LC("lc"),

    /**
     * Liechtenstein
     * 
     */
    
    LI("li"),

    /**
     * Sri Lanka
     * 
     */
    
    LK("lk"),

    /**
     * Liberia
     * 
     */
    
    LR("lr"),

    /**
     * Lesotho
     * 
     */
    
    LS("ls"),

    /**
     * Lithuania
     * 
     */
    
    LT("lt"),

    /**
     * Luxembourg
     * 
     */
    
    LU("lu"),

    /**
     * Latvia
     * 
     */
    
    LV("lv"),

    /**
     * Libyan Arab Jamahiriya
     * 
     */
    
    LY("ly"),

    /**
     * Morocco
     * 
     */
    
    MA("ma"),

    /**
     * Monaco
     * 
     */
    
    MC("mc"),

    /**
     * Moldova, Republic of
     * 
     */
    
    MD("md"),

    /**
     * Madagascar
     * 
     */
    
    MG("mg"),

    /**
     * Marshall Islands
     * 
     */
    
    MH("mh"),

    /**
     * Macedonia, The Former Yugoslav Republic of
     * 
     */
    
    MK("mk"),

    /**
     * Mali
     * 
     */
    
    ML("ml"),

    /**
     * Myanmar
     * 
     */
    
    MM("mm"),

    /**
     * Mongolia
     * 
     */
    
    MN("mn"),

    /**
     * Macau
     * 
     */
    
    MO("mo"),

    /**
     * Northern Mariana Islands
     * 
     */
    
    MP("mp"),

    /**
     * Martinique
     * 
     */
    
    MQ("mq"),

    /**
     * Mauritania
     * 
     */
    
    MR("mr"),

    /**
     * Montserrat
     * 
     */
    
    MS("ms"),

    /**
     * Malta
     * 
     */
    
    MT("mt"),

    /**
     * Mauritius
     * 
     */
    
    MU("mu"),

    /**
     * Maldives
     * 
     */
    
    MV("mv"),

    /**
     * Malawi
     * 
     */
    
    MW("mw"),

    /**
     * Mexico
     * 
     */
    
    MX("mx"),

    /**
     * Malaysia
     * 
     */
    
    MY("my"),

    /**
     * Mozambique
     * 
     */
    
    MZ("mz"),

    /**
     * Namibia
     * 
     */
    
    NA("na"),

    /**
     * New Caledonia
     * 
     */
    
    NC("nc"),

    /**
     * Niger
     * 
     */
    
    NE("ne"),

    /**
     * Norfolk Island
     * 
     */
    
    NF("nf"),

    /**
     * Nigeria
     * 
     */
    
    NG("ng"),

    /**
     * Nicaragua
     * 
     */
    
    NI("ni"),

    /**
     * Netherlands
     * 
     */
    
    NL("nl"),

    /**
     * Norway
     * 
     */
    
    NO("no"),

    /**
     * Nepal
     * 
     */
    
    NP("np"),

    /**
     * Nauru
     * 
     */
    
    NR("nr"),

    /**
     * Niue
     * 
     */
    
    NU("nu"),

    /**
     * New Zealand
     * 
     */
    
    NZ("nz"),

    /**
     * Oman
     * 
     */
    
    OM("om"),

    /**
     * Panama
     * 
     */
    
    PA("pa"),

    /**
     * Peru
     * 
     */
    
    PE("pe"),

    /**
     * French Polynesia
     * 
     */
    
    PF("pf"),

    /**
     * Papua New Guinea
     * 
     */
    
    PG("pg"),

    /**
     * Philippines
     * 
     */
    
    PH("ph"),

    /**
     * Pakistan
     * 
     */
    
    PK("pk"),

    /**
     * Poland
     * 
     */
    
    PL("pl"),

    /**
     * Saint Pierre and Miquelon
     * 
     */
    
    PM("pm"),

    /**
     * Pitcairn Island
     * 
     */
    
    PN("pn"),

    /**
     * Puerto Rico
     * 
     */
    
    PR("pr"),

    /**
     * Palestinian Territories
     * 
     */
    
    PS("ps"),

    /**
     * Portugal
     * 
     */
    
    PT("pt"),

    /**
     * Palau
     * 
     */
    
    PW("pw"),

    /**
     * Paraguay
     * 
     */
    
    PY("py"),

    /**
     * Qatar
     * 
     */
    
    QA("qa"),

    /**
     * Reunion Island
     * 
     */
    
    RE("re"),

    /**
     * Romania
     * 
     */
    
    RO("ro"),

    /**
     * Russian Federation
     * 
     */
    
    RU("ru"),

    /**
     * Rwanda
     * 
     */
    
    RW("rw"),

    /**
     * Saudi Arabia
     * 
     */
    
    SA("sa"),

    /**
     * Solomon Islands
     * 
     */
    
    SB("sb"),

    /**
     * Seychelles
     * 
     */
    
    SC("sc"),

    /**
     * Sudan
     * 
     */
    
    SD("sd"),

    /**
     * Sweden
     * 
     */
    
    SE("se"),

    /**
     * Singapore
     * 
     */
    
    SG("sg"),

    /**
     * Saint Helena
     * 
     */
    
    SH("sh"),

    /**
     * Slovenia
     * 
     */
    
    SI("si"),

    /**
     * Svalbard and Jan Mayen Islands
     * 
     */
    
    SJ("sj"),

    /**
     * Slovak Republic
     * 
     */
    
    SK("sk"),

    /**
     * Sierra Leone
     * 
     */
    
    SL("sl"),

    /**
     * San Marino
     * 
     */
    
    SM("sm"),

    /**
     * Senegal
     * 
     */
    
    SN("sn"),

    /**
     * Somalia
     * 
     */
    
    SO("so"),

    /**
     * Suriname
     * 
     */
    
    SR("sr"),

    /**
     * Sao Tome and Principe
     * 
     */
    
    ST("st"),

    /**
     * El Salvador
     * 
     */
    
    SV("sv"),

    /**
     * Syrian Arab Republic
     * 
     */
    
    SY("sy"),

    /**
     * Swaziland
     * 
     */
    
    SZ("sz"),

    /**
     * Turks and Caicos Islands
     * 
     */
    
    TC("tc"),

    /**
     * Chad
     * 
     */
    
    TD("td"),

    /**
     * French Southern Territories
     * 
     */
    
    TF("tf"),

    /**
     * Togo
     * 
     */
    
    TG("tg"),

    /**
     * Thailand
     * 
     */
    
    TH("th"),

    /**
     * Tajikistan
     * 
     */
    
    TJ("tj"),

    /**
     * Tokelau
     * 
     */
    
    TK("tk"),

    /**
     * Timor-Leste
     * 
     */
    
    TL("tl"),

    /**
     * Turkmenistan
     * 
     */
    
    TM("tm"),

    /**
     * Tunisia
     * 
     */
    
    TN("tn"),

    /**
     * Tonga
     * 
     */
    
    TO("to"),

    /**
     * East Timor
     * 
     */
    
    TP("tp"),

    /**
     * Turkey
     * 
     */
    
    TR("tr"),

    /**
     * Trinidad and Tobago
     * 
     */
    
    TT("tt"),

    /**
     * Tuvalu
     * 
     */
    
    TV("tv"),

    /**
     * Taiwan
     * 
     */
    
    TW("tw"),

    /**
     * Tanzania
     * 
     */
    
    TZ("tz"),

    /**
     * Ukraine
     * 
     */
    
    UA("ua"),

    /**
     * Uganda
     * 
     */
    
    UG("ug"),

    /**
     * United Kingdom
     * 
     */
    
    UK("uk"),

    /**
     * United States Minor Outlying Islands
     * 
     */
    
    UM("um"),

    /**
     * United States
     * 
     */
    
    US("us"),

    /**
     * Uruguay
     * 
     */
    
    UY("uy"),

    /**
     * Uzbekistan
     * 
     */
    
    UZ("uz"),

    /**
     * Holy See (Vatican City State)
     * 
     */
    
    VA("va"),

    /**
     * Saint Vincent and the Grenadines
     * 
     */
    
    VC("vc"),

    /**
     * Venezuela
     * 
     */
    
    VE("ve"),

    /**
     * Virgin Islands, British
     * 
     */
    
    VG("vg"),

    /**
     * Virgin Islands, US
     * 
     */
    
    VI("vi"),

    /**
     * Vietnam
     * 
     */
    
    VN("vn"),

    /**
     * Vanuatu
     * 
     */
    
    VU("vu"),

    /**
     * Wallis and Futuna Islands
     * 
     */
    
    WF("wf"),

    /**
     * Samoa
     * 
     */
    
    WS("ws"),

    /**
     * Yemen
     * 
     */
    
    YE("ye"),

    /**
     * Mayotte
     * 
     */
    
    YT("yt"),

    /**
     * Yugoslavia
     * 
     */
    
    YU("yu"),

    /**
     * South Africa
     * 
     */
    
    ZA("za"),

    /**
     * Zambia
     * 
     */
    
    ZM("zm"),

    /**
     * Zimbabwe
     * 
     */
    
    ZW("zw");
    private final String value;

    IanaCountryTldEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IanaCountryTldEnumeration fromValue(String v) {
        for (IanaCountryTldEnumeration c: IanaCountryTldEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
