//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 03:28:36 PM PST 
//


package uk.org.ifopt.ifopt;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;


public class ValidityCondition {

    protected Date fromDateTime;
    protected Date toDateTime;
    protected String dayType;

    protected List<ValidityCondition.Timebands> timebands;

    /**
     * Gets the value of the fromDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getFromDateTime() {
        return fromDateTime;
    }

    /**
     * Sets the value of the fromDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setFromDateTime(Date value) {
        this.fromDateTime = value;
    }

    /**
     * Gets the value of the toDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getToDateTime() {
        return toDateTime;
    }

    /**
     * Sets the value of the toDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setToDateTime(Date value) {
        this.toDateTime = value;
    }

    /**
     * Gets the value of the dayType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayType() {
        return dayType;
    }

    /**
     * Sets the value of the dayType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayType(String value) {
        this.dayType = value;
    }

    /**
     * Gets the value of the timebands property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timebands property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimebands().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValidityCondition.Timebands }
     * 
     * 
     */
    public List<ValidityCondition.Timebands> getTimebands() {
        if (timebands == null) {
            timebands = new ArrayList<ValidityCondition.Timebands>();
        }
        return this.timebands;
    }

    public static class Timebands {

        protected Timeband timeband;

        /**
         * Gets the value of the timeband property.
         * 
         * @return
         *     possible object is
         *     {@link Timeband }
         *     
         */
        public Timeband getTimeband() {
            return timeband;
        }

        /**
         * Sets the value of the timeband property.
         * 
         * @param value
         *     allowed object is
         *     {@link Timeband }
         *     
         */
        public void setTimeband(Timeband value) {
            this.timeband = value;
        }

    }

}
